// Code generated by Icestudio 0.9.0

`default_nettype none

//---- Top entity
module main (
 input v42529f,
 input va68b7a,
 input vd7bd9f,
 output [7:0] v87668b,
 output vf35ecc,
 output [0:7] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire [0:7] w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire w38;
 wire w39;
 wire w40;
 wire w41;
 wire w42;
 wire w43;
 wire w44;
 assign w0 = vd7bd9f;
 assign vf35ecc = w7;
 assign w9 = va68b7a;
 assign v87668b = w10;
 assign w19 = v42529f;
 assign w23 = v42529f;
 assign w26 = v42529f;
 assign w29 = v42529f;
 assign w32 = v42529f;
 assign w35 = v42529f;
 assign w38 = v42529f;
 assign w41 = v42529f;
 assign w44 = v42529f;
 assign w12 = w11;
 assign w13 = w11;
 assign w13 = w12;
 assign w14 = w11;
 assign w14 = w12;
 assign w14 = w13;
 assign w15 = w11;
 assign w15 = w12;
 assign w15 = w13;
 assign w15 = w14;
 assign w16 = w11;
 assign w16 = w12;
 assign w16 = w13;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w11;
 assign w17 = w12;
 assign w17 = w13;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 assign w18 = w11;
 assign w18 = w12;
 assign w18 = w13;
 assign w18 = w14;
 assign w18 = w15;
 assign w18 = w16;
 assign w18 = w17;
 assign w22 = w1;
 assign w23 = w19;
 assign w25 = w2;
 assign w26 = w19;
 assign w26 = w23;
 assign w28 = w3;
 assign w29 = w19;
 assign w29 = w23;
 assign w29 = w26;
 assign w31 = w4;
 assign w32 = w19;
 assign w32 = w23;
 assign w32 = w26;
 assign w32 = w29;
 assign w34 = w5;
 assign w35 = w19;
 assign w35 = w23;
 assign w35 = w26;
 assign w35 = w29;
 assign w35 = w32;
 assign w37 = w6;
 assign w38 = w19;
 assign w38 = w23;
 assign w38 = w26;
 assign w38 = w29;
 assign w38 = w32;
 assign w38 = w35;
 assign w40 = w8;
 assign w41 = w19;
 assign w41 = w23;
 assign w41 = w26;
 assign w41 = w29;
 assign w41 = w32;
 assign w41 = w35;
 assign w41 = w38;
 assign w43 = w7;
 assign w44 = w19;
 assign w44 = w23;
 assign w44 = w26;
 assign w44 = w29;
 assign w44 = w32;
 assign w44 = w35;
 assign w44 = w38;
 assign w44 = w41;
 v70ff7f v027c1e (
  .vef4cea(w0),
  .vc24d9f(w1),
  .vb55943(w12)
 );
 v70ff7f vcc08b8 (
  .vef4cea(w1),
  .vc24d9f(w2),
  .vb55943(w11)
 );
 v70ff7f v2c951a (
  .vef4cea(w2),
  .vc24d9f(w3),
  .vb55943(w13)
 );
 v70ff7f v5cd36e (
  .vef4cea(w3),
  .vc24d9f(w4),
  .vb55943(w14)
 );
 v70ff7f v2423a4 (
  .vef4cea(w4),
  .vc24d9f(w5),
  .vb55943(w15)
 );
 v70ff7f vaa8638 (
  .vef4cea(w5),
  .vc24d9f(w6),
  .vb55943(w16)
 );
 v70ff7f vfd0dfd (
  .vef4cea(w6),
  .vc24d9f(w8),
  .vb55943(w17)
 );
 v70ff7f va9b42f (
  .vc24d9f(w7),
  .vef4cea(w8),
  .vb55943(w18)
 );
 v96f098 vff8a8e (
  .v0e28cb(w9),
  .vcbab45(w20)
 );
 main_v9434f3 v9434f3 (
  .o(w10),
  .i7(w21),
  .i6(w24),
  .i5(w27),
  .i4(w30),
  .i3(w33),
  .i2(w36),
  .i1(w39),
  .i0(w42)
 );
 v7ebc90 v41f048 (
  .vcbab45(w11),
  .v0e28cb(w19),
  .v3ca442(w20)
 );
 v70ff7f vdec3fc (
  .vc24d9f(w21),
  .vef4cea(w22),
  .vb55943(w23)
 );
 v70ff7f v750d37 (
  .vc24d9f(w24),
  .vef4cea(w25),
  .vb55943(w26)
 );
 v70ff7f v3bea11 (
  .vc24d9f(w27),
  .vef4cea(w28),
  .vb55943(w29)
 );
 v70ff7f vcd83d0 (
  .vc24d9f(w30),
  .vef4cea(w31),
  .vb55943(w32)
 );
 v70ff7f vd6a48f (
  .vc24d9f(w33),
  .vef4cea(w34),
  .vb55943(w35)
 );
 v70ff7f vd3ed5f (
  .vc24d9f(w36),
  .vef4cea(w37),
  .vb55943(w38)
 );
 v70ff7f v4071e0 (
  .vc24d9f(w39),
  .vef4cea(w40),
  .vb55943(w41)
 );
 v70ff7f v9202fc (
  .vc24d9f(w42),
  .vef4cea(w43),
  .vb55943(w44)
 );
 assign vinit = 8'b00000000;
endmodule

//---- Top entity
module v70ff7f (
 input vb55943,
 input vef4cea,
 output vc24d9f
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = vef4cea;
 assign w1 = vb55943;
 assign vc24d9f = w2;
 v70ff7f_v526aa2 v526aa2 (
  .d(w0),
  .clk(w1),
  .q(w2)
 );
endmodule

//---------------------------------------------------
//-- Flip-flop D
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Delay flip-flop
//---------------------------------------------------

module v70ff7f_v526aa2 (
 input clk,
 input d,
 output q
);
 // D flip-flop
 
 reg q = 1'b0;
 
 always @(posedge clk)
 begin
   q <= d;
 end
 
 
endmodule
//---- Top entity
module v96f098 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v96f098_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT logic gate
//---------------------------------------------------

module v96f098_vd54ca1 (
 input a,
 output c
);
 // NOT logic gate
 
 assign c = ~ a;
endmodule
//---- Top entity
module v7ebc90 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v7ebc90_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AND logic gate
//---------------------------------------------------

module v7ebc90_vf4938a (
 input a,
 input b,
 output c
);
 // AND logic gate
 
 assign c = a & b;
endmodule

module main_v9434f3 (
 input i7,
 input i6,
 input i5,
 input i4,
 input i3,
 input i2,
 input i1,
 input i0,
 output [7:0] o
);
 assign o = {i0, i1, i2, i3, i4, i5, i6, i7};
endmodule
