// Code generated by Icestudio 0.9.0

`default_nettype none

//---- Top entity
module main #(
 parameter v03c634 = 9,
 parameter v3d07ba = 0,
 parameter v1bb386 = 0,
 parameter v7cb1a2 = 10000,
 parameter v986bb1 = "sine.list",
 parameter v4381cb = 100,
 parameter v2a0a3f = 15,
 parameter v174b86 = 16383,
 parameter vd3aaba = -16383,
 parameter v177d29 = "v177d29.list",
 parameter v6f325e = "v6f325e.list"
) (
 input vclk,
 output v0c4498,
 output v74ab9d,
 output vb7ae1c,
 output vb96364,
 output ve6e8ca,
 output vd93e69,
 output v69e493,
 output v4cfd20,
 output vb469f3
);
 localparam p0 = v7cb1a2;
 localparam p2 = v4381cb;
 localparam p5 = v3d07ba;
 localparam p6 = v03c634;
 localparam p7 = v1bb386;
 localparam p8 = v2a0a3f;
 localparam p16 = v174b86;
 localparam p19 = vd3aaba;
 localparam p21 = v986bb1;
 localparam p23 = v6f325e;
 wire w1;
 wire w3;
 wire w4;
 wire [0:15] w9;
 wire [0:15] w10;
 wire [0:15] w11;
 wire w12;
 wire w13;
 wire [0:15] w14;
 wire w15;
 wire [0:15] w17;
 wire [0:15] w18;
 wire [0:15] w20;
 wire [0:11] w22;
 wire [0:3] w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire [0:7] w35;
 wire [0:15] w36;
 wire w37;
 wire w38;
 wire w39;
 wire w40;
 assign v0c4498 = w13;
 assign v74ab9d = w25;
 assign vb7ae1c = w26;
 assign vb96364 = w27;
 assign ve6e8ca = w28;
 assign vd93e69 = w29;
 assign v69e493 = w30;
 assign v4cfd20 = w31;
 assign vb469f3 = w32;
 assign w40 = vclk;
 assign w14 = w9;
 assign w15 = w13;
 assign w33 = w1;
 assign w37 = w4;
 assign w38 = w4;
 assign w38 = w37;
 assign w39 = w4;
 assign w39 = w37;
 assign w39 = w38;
 main_v6e4b35 #(
  .N(p0)
 ) v6e4b35 (
  .clk_out(w3),
  .clk_in(w4)
 );
 main_vdb0040 #(
  .N(p2)
 ) vdb0040 (
  .clk_out(w1),
  .clk_in(w3)
 );
 ve2b7eb #(
  .vecb3d5(p5),
  .ve58c06(p6),
  .v204bed(p7)
 ) ve3c290 (
  .v3ead5b(w4),
  .v328508(w40)
 );
 v2dfa72 v3b78d3 (
  .vdb3006(w9),
  .v2ba137(w10),
  .v356dbf(w36)
 );
 v625333 #(
  .vaf1d6e(p8)
 ) vcc6fa1 (
  .vb6a5b5(w9),
  .v7ff276(w12)
 );
 v2dfa72 v698310 (
  .vdb3006(w11),
  .v2ba137(w14),
  .v356dbf(w18)
 );
 v6bd4c0 ve5834d (
  .v3f90b8(w10),
  .vc320da(w11),
  .v6dda25(w37)
 );
 v96f098 vac33ad (
  .v0e28cb(w12),
  .vcbab45(w13)
 );
 v1f5ce5 v7981d5 (
  .v2d3366(w15),
  .v17f43d(w17),
  .ve0f053(w18),
  .v0792df(w20)
 );
 v34688e #(
  .vc5c8ea(p16)
 ) v601465 (
  .v366f99(w17)
 );
 v34688e #(
  .vc5c8ea(p19)
 ) vd450d3 (
  .v366f99(w20)
 );
 v0ee3aa v584cff (
  .vaf2fc7(w22),
  .ve556f1(w34),
  .v6dda25(w38)
 );
 main_v273ad7 #(
  .ROMFILE(p21)
 ) v273ad7 (
  .A(w22),
  .D(w36),
  .clk(w39)
 );
 main_vb22799 vb22799 (
  .clk_in(w1),
  .out(w24)
 );
 main_vc78599 #(
  .ROMFILE(p23)
 ) vc78599 (
  .A(w24),
  .clk(w33),
  .D(w35)
 );
 vbc6704 vce5153 (
  .vc85478(w25),
  .v7ada3f(w26),
  .v2c9812(w27),
  .ve0c1b4(w28),
  .v7c37b3(w29),
  .v8f149e(w30),
  .vb85197(w31),
  .v45ab8c(w32),
  .v595263(w35)
 );
 vc4dd08 v02a27d (
  .v608bd9(w34)
 );
endmodule

//---- Top entity
module ve2b7eb #(
 parameter ve58c06 = 0,
 parameter vecb3d5 = 79,
 parameter v204bed = 4,
 parameter vd29ea2 = 1,
 parameter v16d365 = "SIMPLE"
) (
 input v328508,
 output vdbfa46,
 output v3ead5b,
 output v333bf4
);
 localparam p0 = ve58c06;
 localparam p1 = vecb3d5;
 localparam p2 = v204bed;
 localparam p3 = vd29ea2;
 localparam p4 = v16d365;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 assign vdbfa46 = w7;
 assign v3ead5b = w8;
 assign v333bf4 = w9;
 assign w10 = v328508;
 vc83dcd va0dc84 (
  .v608bd9(w5)
 );
 vc4dd08 vda5929 (
  .v608bd9(w6)
 );
 ve2b7eb_vd4bd9d #(
  .DIVR(p0),
  .DIVF(p1),
  .DIVQ(p2),
  .FILTER_RANGE(p3),
  .FEEDBACK_PATH(p4)
 ) vd4bd9d (
  .RESETB(w5),
  .BYPASS(w6),
  .PLLOUTGLOBAL(w7),
  .PLLOUTCORE(w8),
  .LOCK(w9),
  .PACKAGEPIN(w10)
 );
endmodule

//---------------------------------------------------
//-- PLL40_PAD
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- SB_PLL40_PAD
//---------------------------------------------------

module ve2b7eb_vd4bd9d #(
 parameter DIVR = 0,
 parameter DIVF = 0,
 parameter DIVQ = 0,
 parameter FILTER_RANGE = 0,
 parameter FEEDBACK_PATH = 0
) (
 input PACKAGEPIN,
 input RESETB,
 input BYPASS,
 output PLLOUTGLOBAL,
 output PLLOUTCORE,
 output LOCK
);
 SB_PLL40_PAD #(
 		.FEEDBACK_PATH("SIMPLE"),
 		.DIVR(DIVR),		// DIVR =  0
 		.DIVF(DIVF),	// DIVF = 79
 		.DIVQ(DIVQ),		// DIVQ =  4
 		.FILTER_RANGE(FILTER_RANGE)	// FILTER_RANGE = 1
 	) uut (
 		.LOCK(LOCK),
 		.RESETB(RESETB),
 		.BYPASS(BYPASS),
 		.PACKAGEPIN(PACKAGEPIN),
 		.PLLOUTCORE(PLLOUTCORE),
 		.PLLOUTGLOBAL(PLLOUTGLOBAL)
 		);
endmodule
//---- Top entity
module vc83dcd (
 output v608bd9
);
 wire w0;
 assign v608bd9 = w0;
 vc83dcd_v68c173 v68c173 (
  .v(w0)
 );
endmodule

//---------------------------------------------------
//-- Bit 1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Assign 1 to the output wire
//---------------------------------------------------

module vc83dcd_v68c173 (
 output v
);
 // Bit 1
 
 assign v = 1'b1;
endmodule
//---- Top entity
module vc4dd08 (
 output v608bd9
);
 wire w0;
 assign v608bd9 = w0;
 vc4dd08_v68c173 v68c173 (
  .v(w0)
 );
endmodule

//---------------------------------------------------
//-- Bit 0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Assign 0 to the output wire
//---------------------------------------------------

module vc4dd08_v68c173 (
 output v
);
 // Bit 0
 
 assign v = 1'b0;
endmodule
//---- Top entity
module v2dfa72 #(
 parameter v52d4a9 = 16
) (
 input [15:0] v356dbf,
 input [15:0] v2ba137,
 output [15:0] vdb3006,
 output vfeefc7,
 output v0f5b9c
);
 localparam p5 = v52d4a9;
 wire [0:15] w0;
 wire [0:15] w1;
 wire w2;
 wire w3;
 wire [0:15] w4;
 assign w0 = v356dbf;
 assign w1 = v2ba137;
 assign vfeefc7 = w2;
 assign v0f5b9c = w3;
 assign vdb3006 = w4;
 v2dfa72_ve6b254 #(
  .N(p5)
 ) ve6b254 (
  .a(w0),
  .b(w1),
  .clipMaxInt(w2),
  .clipMinInt(w3),
  .y(w4)
 );
endmodule

//---------------------------------------------------
//-- add_int16_sat
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 16 bits signed integer add with minint,maxint saturation
//---------------------------------------------------

module v2dfa72_ve6b254 #(
 parameter N = 0
) (
 input [15:0] a,
 input [15:0] b,
 output [15:0] y,
 output clipMaxInt,
 output clipMinInt
);
 // y = a + b;  signed N bits integers, coerce sum y in [-32768..32767 range]
 
 localparam N_M1 = N - 1;
   
 wire signed [N:0] Sum_N_P1_bits;
 wire y_less_than_MININT;
 wire y_more_than_MAXINT;
 
 wire signed [N_M1:0] MININT = {1'b1,{N_M1{1'b0}}};
 wire signed [N_M1:0] MAXINT = {1'b0,{N_M1{1'b1}}};
 
 assign Sum_N_P1_bits = $signed(a) + $signed(b);
 assign y_less_than_MININT = Sum_N_P1_bits[N:N_M1] == 2'b10;
 assign y_more_than_MAXINT = Sum_N_P1_bits[N:N_M1] == 2'b01;
 
 assign y = y_less_than_MININT ? MININT : y_more_than_MAXINT ? MAXINT : Sum_N_P1_bits[N_M1:0];
 
endmodule
//---- Top entity
module v625333 #(
 parameter vaf1d6e = 0
) (
 input [15:0] vb6a5b5,
 output v7ff276
);
 localparam p0 = vaf1d6e;
 wire w1;
 wire [0:15] w2;
 assign v7ff276 = w1;
 assign w2 = vb6a5b5;
 v625333_vd80544 #(
  .BIT(p0)
 ) vd80544 (
  .o(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Extract-1-bit-16bit-bus
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Extractor de 1 bit de un bus de 16 bits
//---------------------------------------------------

module v625333_vd80544 #(
 parameter BIT = 0
) (
 input [15:0] i,
 output o
);
 assign o = i[BIT];
endmodule
//---- Top entity
module v6bd4c0 (
 input v6dda25,
 input [15:0] vc320da,
 output [15:0] v3f90b8
);
 wire [0:15] w0;
 wire [0:15] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 assign w0 = vc320da;
 assign v3f90b8 = w1;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 v852bc8 vd47660 (
  .v91b9c1(w0),
  .v527ffb(w2),
  .v71a717(w3),
  .v0b337e(w4),
  .vfc89f9(w5)
 );
 v401a28 v3ef916 (
  .v14a530(w1),
  .vcc76e8(w6),
  .vd531e6(w7),
  .v7ef7d6(w8),
  .v1447f2(w9)
 );
 vc12f0f vd70fdb (
  .v7c67e1(w5),
  .vf6ad19(w9),
  .v6dda25(w10)
 );
 vc12f0f v8c7a79 (
  .v7c67e1(w4),
  .vf6ad19(w8),
  .v6dda25(w11)
 );
 vc12f0f v132776 (
  .v7c67e1(w3),
  .vf6ad19(w7),
  .v6dda25(w12)
 );
 vc12f0f v1937e6 (
  .v7c67e1(w2),
  .vf6ad19(w6),
  .v6dda25(w13)
 );
endmodule

//---------------------------------------------------
//-- DFF-x16
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-x16: 16 D flip-flops in paralell
//---------------------------------------------------
//---- Top entity
module v852bc8 (
 input [15:0] v91b9c1,
 output [3:0] vfc89f9,
 output [3:0] v0b337e,
 output [3:0] v71a717,
 output [3:0] v527ffb
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 assign w0 = v91b9c1;
 assign v527ffb = w1;
 assign v71a717 = w2;
 assign v0b337e = w3;
 assign vfc89f9 = w4;
 v852bc8_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Split-quarter
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Split-quarter: Split the 16-bits bus into four buses of the same size
//---------------------------------------------------

module v852bc8_v9a2a06 (
 input [15:0] i,
 output [3:0] o3,
 output [3:0] o2,
 output [3:0] o1,
 output [3:0] o0
);
 assign o3 = i[15:12];
 assign o2 = i[11:8];
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v401a28 (
 input [3:0] v1447f2,
 input [3:0] v7ef7d6,
 input [3:0] vd531e6,
 input [3:0] vcc76e8,
 output [15:0] v14a530
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 assign v14a530 = w0;
 assign w1 = vcc76e8;
 assign w2 = vd531e6;
 assign w3 = v7ef7d6;
 assign w4 = v1447f2;
 v401a28_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Join-quarter
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Join-quarter: Join the four same buses into an 16-bits Bus
//---------------------------------------------------

module v401a28_v9a2a06 (
 input [3:0] i3,
 input [3:0] i2,
 input [3:0] i1,
 input [3:0] i0,
 output [15:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module vc12f0f (
 input v6dda25,
 input [3:0] v7c67e1,
 output [3:0] vf6ad19
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 assign w6 = v7c67e1;
 assign vf6ad19 = w7;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 vc4f23a v390ed9 (
  .v3f8943(w0),
  .v64d863(w1),
  .vda577d(w4),
  .v985fcb(w6),
  .v4f1fd3(w8)
 );
 v84f0a1 v0e8f25 (
  .v03aaf0(w2),
  .vee8a83(w3),
  .vf8041d(w5),
  .v11bca5(w7),
  .vd84a57(w9)
 );
 v053dc2 vb95ccb (
  .vf54559(w1),
  .ve8318d(w2),
  .va4102a(w13)
 );
 v053dc2 v736168 (
  .vf54559(w0),
  .ve8318d(w3),
  .va4102a(w12)
 );
 v053dc2 ve8ed3a (
  .vf54559(w4),
  .ve8318d(w5),
  .va4102a(w11)
 );
 v053dc2 vbdfdbf (
  .vf54559(w8),
  .ve8318d(w9),
  .va4102a(w10)
 );
endmodule

//---------------------------------------------------
//-- DFF-x04
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-04: Three D flip-flops in paralell
//---------------------------------------------------
//---- Top entity
module vc4f23a (
 input [3:0] v985fcb,
 output v4f1fd3,
 output vda577d,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign vda577d = w2;
 assign v4f1fd3 = w3;
 assign w4 = v985fcb;
 vc4f23a_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .o2(w2),
  .o3(w3),
  .i(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Split-all: Split the 4-bits bus into its wires
//---------------------------------------------------

module vc4f23a_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v84f0a1 (
 input vd84a57,
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [3:0] v11bca5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign w2 = vf8041d;
 assign w3 = vd84a57;
 assign v11bca5 = w4;
 v84f0a1_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .i2(w2),
  .i3(w3),
  .o(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Join-all: Join all the wires into a 4-bits Bus
//---------------------------------------------------

module v84f0a1_v9a2a06 (
 input i3,
 input i2,
 input i1,
 input i0,
 output [3:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module v053dc2 #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v053dc2_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- DFF
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- D Flip-flop (verilog implementation)
//---------------------------------------------------

module v053dc2_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg q = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   q <= d;
endmodule
//---- Top entity
module v96f098 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v96f098_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT logic gate
//---------------------------------------------------

module v96f098_vd54ca1 (
 input a,
 output c
);
 // NOT logic gate
 
 assign c = ~ a;
endmodule
//---- Top entity
module v1f5ce5 (
 input [15:0] v0792df,
 input [15:0] v17f43d,
 input v2d3366,
 output [15:0] ve0f053
);
 wire [0:7] w0;
 wire [0:15] w1;
 wire [0:15] w2;
 wire [0:7] w3;
 wire [0:15] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire w8;
 wire w9;
 wire [0:7] w10;
 assign w1 = v17f43d;
 assign w2 = v0792df;
 assign ve0f053 = w4;
 assign w8 = v2d3366;
 assign w9 = v2d3366;
 assign w9 = w8;
 v1bbb5b v41cfb0 (
  .v9d2a6a(w0),
  .v2a1cbe(w7),
  .v2d3366(w9),
  .v9d7ae8(w10)
 );
 v306ca3 ve04806 (
  .v91b9c1(w1),
  .vef5eee(w6),
  .vd3ef3b(w10)
 );
 v306ca3 v4549dd (
  .v91b9c1(w2),
  .vef5eee(w5),
  .vd3ef3b(w7)
 );
 v1bbb5b vf7893e (
  .v9d2a6a(w3),
  .v2a1cbe(w5),
  .v9d7ae8(w6),
  .v2d3366(w8)
 );
 v8cc49c v5ec84b (
  .v2b8a97(w0),
  .vb334ae(w3),
  .v14a530(w4)
 );
endmodule

//---------------------------------------------------
//-- 16-bits-Mux-2-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2-to-1 Multplexer (16-bit channels)
//---------------------------------------------------
//---- Top entity
module v1bbb5b (
 input [7:0] v2a1cbe,
 input [7:0] v9d7ae8,
 input v2d3366,
 output [7:0] v9d2a6a
);
 wire [0:3] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:3] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire [0:3] w10;
 assign v9d2a6a = w1;
 assign w2 = v2a1cbe;
 assign w3 = v9d7ae8;
 assign w8 = v2d3366;
 assign w9 = v2d3366;
 assign w9 = w8;
 v952eda v54aed2 (
  .v6833fd(w0),
  .v54ac99(w7),
  .v2d3366(w9),
  .ve2616d(w10)
 );
 vafb28f v117a88 (
  .v3c88fc(w0),
  .va9ac17(w1),
  .v515fe7(w4)
 );
 v6bdcd9 v9f32ae (
  .vcc8c7c(w2),
  .v651522(w5),
  .v2cc41f(w7)
 );
 v6bdcd9 v9881c7 (
  .vcc8c7c(w3),
  .v651522(w6),
  .v2cc41f(w10)
 );
 v952eda v34a43a (
  .v6833fd(w4),
  .v54ac99(w5),
  .ve2616d(w6),
  .v2d3366(w8)
 );
endmodule

//---------------------------------------------------
//-- 8-bits-Mux-2-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2-to-1 Multplexer (8-bit channels)
//---------------------------------------------------
//---- Top entity
module v952eda (
 input [3:0] v54ac99,
 input [3:0] ve2616d,
 input v2d3366,
 output [3:0] v6833fd
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:3] w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 assign v6833fd = w3;
 assign w5 = ve2616d;
 assign w6 = v54ac99;
 assign w9 = v2d3366;
 assign w10 = v2d3366;
 assign w11 = v2d3366;
 assign w12 = v2d3366;
 assign w10 = w9;
 assign w11 = w9;
 assign w11 = w10;
 assign w12 = w9;
 assign w12 = w10;
 assign w12 = w11;
 vd0c4e5 v6d94c9 (
  .v030ad0(w0),
  .v2d3366(w11),
  .v27dec4(w15),
  .vb192d0(w17)
 );
 vd0c4e5 vebe465 (
  .v030ad0(w1),
  .v2d3366(w12),
  .v27dec4(w16),
  .vb192d0(w18)
 );
 vd0c4e5 ve1c21f (
  .v030ad0(w2),
  .v2d3366(w10),
  .v27dec4(w13),
  .vb192d0(w14)
 );
 v84f0a1 va44bdf (
  .vee8a83(w0),
  .v03aaf0(w1),
  .vf8041d(w2),
  .v11bca5(w3),
  .vd84a57(w4)
 );
 vd0c4e5 v2ebff3 (
  .v030ad0(w4),
  .v27dec4(w7),
  .vb192d0(w8),
  .v2d3366(w9)
 );
 vc4f23a v3c3a57 (
  .v985fcb(w5),
  .v4f1fd3(w8),
  .vda577d(w14),
  .v3f8943(w17),
  .v64d863(w18)
 );
 vc4f23a vd6d480 (
  .v985fcb(w6),
  .v4f1fd3(w7),
  .vda577d(w13),
  .v3f8943(w15),
  .v64d863(w16)
 );
endmodule

//---------------------------------------------------
//-- 4-bits-Mux-2-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2-to-1 Multplexer (4-bit channels)
//---------------------------------------------------
//---- Top entity
module vd0c4e5 (
 input v27dec4,
 input vb192d0,
 input v2d3366,
 output v030ad0
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign v030ad0 = w0;
 assign w2 = v2d3366;
 assign w3 = v2d3366;
 assign w6 = v27dec4;
 assign w7 = vb192d0;
 assign w3 = w2;
 v873425 vaaee1f (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w4)
 );
 vba518e v569873 (
  .vcbab45(w1),
  .v3ca442(w2),
  .v0e28cb(w6)
 );
 v3676a0 v1f00ae (
  .v0e28cb(w3),
  .vcbab45(w5)
 );
 vba518e vc8527f (
  .vcbab45(w4),
  .v3ca442(w5),
  .v0e28cb(w7)
 );
endmodule

//---------------------------------------------------
//-- Mux-2-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2-to-1 Multplexer (1-bit channels)
//---------------------------------------------------
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR2: Two bits input OR gate
//---------------------------------------------------

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Two bits input And gate
//---------------------------------------------------

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT gate (Verilog implementation)
//---------------------------------------------------

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
//---- Top entity
module vafb28f (
 input [3:0] v515fe7,
 input [3:0] v3c88fc,
 output [7:0] va9ac17
);
 wire [0:7] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign va9ac17 = w0;
 assign w1 = v515fe7;
 assign w2 = v3c88fc;
 vafb28f_v9a2a06 v9a2a06 (
  .o(w0),
  .i1(w1),
  .i0(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus8-Join-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus8-Join-half: Join the two same halves into an 8-bits Bus
//---------------------------------------------------

module vafb28f_v9a2a06 (
 input [3:0] i1,
 input [3:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v6bdcd9 (
 input [7:0] vcc8c7c,
 output [3:0] v651522,
 output [3:0] v2cc41f
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign v651522 = w0;
 assign v2cc41f = w1;
 assign w2 = vcc8c7c;
 v6bdcd9_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus8-Split-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus8-Split-half: Split the 8-bits bus into two buses of the same size
//---------------------------------------------------

module v6bdcd9_v9a2a06 (
 input [7:0] i,
 output [3:0] o1,
 output [3:0] o0
);
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v306ca3 (
 input [15:0] v91b9c1,
 output [7:0] vef5eee,
 output [7:0] vd3ef3b
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = v91b9c1;
 assign vef5eee = w1;
 assign vd3ef3b = w2;
 v306ca3_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Split-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Split-half: Split the 16-bits bus into two buses of the same size
//---------------------------------------------------

module v306ca3_v9a2a06 (
 input [15:0] i,
 output [7:0] o1,
 output [7:0] o0
);
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module v8cc49c (
 input [7:0] vb334ae,
 input [7:0] v2b8a97,
 output [15:0] v14a530
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v14a530 = w0;
 assign w1 = v2b8a97;
 assign w2 = vb334ae;
 v8cc49c_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Join-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Join-half: Join the two same halves into an 16-bits Bus
//---------------------------------------------------

module v8cc49c_v9a2a06 (
 input [7:0] i1,
 input [7:0] i0,
 output [15:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v34688e #(
 parameter vc5c8ea = 0
) (
 output [15:0] v366f99
);
 localparam p0 = vc5c8ea;
 wire [0:15] w1;
 assign v366f99 = w1;
 v34688e_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- Constante-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Valor genérico constante, de 16 bits. Su valor se introduce como parámetro. Por defecto vale 0
//---------------------------------------------------

module v34688e_v465065 #(
 parameter VALUE = 0
) (
 output [15:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v0ee3aa (
 input v6dda25,
 input ve556f1,
 output [11:0] vaf2fc7,
 output ve37344
);
 wire w0;
 wire [0:11] w1;
 wire [0:11] w2;
 wire w3;
 wire [0:11] w4;
 wire w5;
 assign w0 = ve556f1;
 assign w3 = v6dda25;
 assign vaf2fc7 = w4;
 assign ve37344 = w5;
 assign w4 = w1;
 vfc56d8 vbed1b5 (
  .v782748(w0),
  .ve3ae29(w1),
  .v6d2729(w2),
  .v6dda25(w3)
 );
 v135101 v95790d (
  .vfe37b3(w1),
  .v937355(w2),
  .v4642b6(w5)
 );
endmodule

//---------------------------------------------------
//-- syscounter-rst-12bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 12-bits Syscounter with reset
//---------------------------------------------------
//---- Top entity
module vfc56d8 (
 input v6dda25,
 input v782748,
 input [11:0] v6d2729,
 output [11:0] ve3ae29
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 wire [0:3] w5;
 wire [0:11] w6;
 wire [0:11] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 assign w6 = v6d2729;
 assign ve3ae29 = w7;
 assign w8 = v6dda25;
 assign w9 = v6dda25;
 assign w10 = v6dda25;
 assign w11 = v782748;
 assign w12 = v782748;
 assign w13 = v782748;
 assign w9 = w8;
 assign w10 = w8;
 assign w10 = w9;
 assign w12 = w11;
 assign w13 = w11;
 assign w13 = w12;
 v5c75f6 vbdef88 (
  .v4de61b(w0),
  .v50034e(w3),
  .v6dda25(w10),
  .v782748(w13)
 );
 v5c75f6 v6188f9 (
  .v4de61b(w1),
  .v50034e(w4),
  .v6dda25(w9),
  .v782748(w12)
 );
 v5c75f6 v9f7443 (
  .v4de61b(w2),
  .v50034e(w5),
  .v6dda25(w8),
  .v782748(w11)
 );
 veed20e v30892d (
  .v4cb892(w0),
  .v51ed6c(w1),
  .v9174ea(w2),
  .v1215c2(w6)
 );
 vaa90c2 v07d62d (
  .vad5e06(w3),
  .v446218(w4),
  .v563cc4(w5),
  .vb04f06(w7)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x12
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x12: 12 D flip-flops in paralell with reset
//---------------------------------------------------
//---- Top entity
module v5c75f6 (
 input v6dda25,
 input v782748,
 input [3:0] v4de61b,
 output [3:0] v50034e
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w6 = v4de61b;
 assign v50034e = w7;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w14 = v782748;
 assign w15 = v782748;
 assign w16 = v782748;
 assign w17 = v782748;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w15 = w14;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 vc4f23a v4b1225 (
  .v3f8943(w2),
  .v64d863(w3),
  .vda577d(w4),
  .v985fcb(w6),
  .v4f1fd3(w8)
 );
 v84f0a1 v6491fd (
  .v03aaf0(w0),
  .vee8a83(w1),
  .vf8041d(w5),
  .v11bca5(w7),
  .vd84a57(w9)
 );
 v2be0f8 v10a04f (
  .v4642b6(w0),
  .vf354ee(w3),
  .vd53b77(w13),
  .v27dec4(w17)
 );
 v2be0f8 v7d9648 (
  .v4642b6(w1),
  .vf354ee(w2),
  .vd53b77(w12),
  .v27dec4(w16)
 );
 v2be0f8 v004b14 (
  .vf354ee(w4),
  .v4642b6(w5),
  .vd53b77(w11),
  .v27dec4(w15)
 );
 v2be0f8 v8aa818 (
  .vf354ee(w8),
  .v4642b6(w9),
  .vd53b77(w10),
  .v27dec4(w14)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x04
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x04: Three D flip-flops in paralell with reset
//---------------------------------------------------
//---- Top entity
module v2be0f8 #(
 parameter vbd3217 = 0
) (
 input vd53b77,
 input v27dec4,
 input vf354ee,
 output v4642b6
);
 localparam p5 = vbd3217;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w6;
 assign w2 = v27dec4;
 assign w3 = vf354ee;
 assign v4642b6 = w4;
 assign w6 = vd53b77;
 v3676a0 v7539bf (
  .vcbab45(w1),
  .v0e28cb(w2)
 );
 vba518e vfe8158 (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w3)
 );
 v053dc2 #(
  .v71e305(p5)
 ) vd104a4 (
  .vf54559(w0),
  .ve8318d(w4),
  .va4102a(w6)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x01
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x01: D Flip flop with reset input. When rst=1, the DFF is 0
//---------------------------------------------------
//---- Top entity
module veed20e (
 input [11:0] v1215c2,
 output [3:0] v9174ea,
 output [3:0] v51ed6c,
 output [3:0] v4cb892
);
 wire [0:11] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 assign w0 = v1215c2;
 assign v9174ea = w1;
 assign v51ed6c = w2;
 assign v4cb892 = w3;
 veed20e_v9a2a06 v9a2a06 (
  .i(w0),
  .o2(w1),
  .o1(w2),
  .o0(w3)
 );
endmodule

//---------------------------------------------------
//-- Bus12-Split-one-third
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus12-Split-one-third: Split the 12-bits bus into three buses of equal size
//---------------------------------------------------

module veed20e_v9a2a06 (
 input [11:0] i,
 output [3:0] o2,
 output [3:0] o1,
 output [3:0] o0
);
 
 assign o2 = i[11:8];
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module vaa90c2 (
 input [3:0] v563cc4,
 input [3:0] v446218,
 input [3:0] vad5e06,
 output [11:0] vb04f06
);
 wire [0:11] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 assign vb04f06 = w0;
 assign w1 = vad5e06;
 assign w2 = v446218;
 assign w3 = v563cc4;
 vaa90c2_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3)
 );
endmodule

//---------------------------------------------------
//-- Bus12-Join-one-third
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus12-Join-one-third: Join the three buses into an 12-bits Bus
//---------------------------------------------------

module vaa90c2_v9a2a06 (
 input [3:0] i2,
 input [3:0] i1,
 input [3:0] i0,
 output [11:0] o
);
 assign o = {i2, i1, i0};
 
endmodule
//---- Top entity
module v135101 #(
 parameter v6c5139 = 1
) (
 input [11:0] vfe37b3,
 output v4642b6,
 output [11:0] v937355
);
 localparam p1 = v6c5139;
 wire w0;
 wire [0:11] w2;
 wire [0:11] w3;
 assign v4642b6 = w0;
 assign w2 = vfe37b3;
 assign v937355 = w3;
 vab5c5a #(
  .vd73390(p1)
 ) v87b9c7 (
  .v4642b6(w0),
  .v9f67dc(w2),
  .v9a4127(w3)
 );
endmodule

//---------------------------------------------------
//-- Inc1-12bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Inc1-12bit: Increment a 12-bits number by one
//---------------------------------------------------
//---- Top entity
module vab5c5a #(
 parameter vd73390 = 0
) (
 input [11:0] v9f67dc,
 output v4642b6,
 output [11:0] v9a4127
);
 localparam p1 = vd73390;
 wire w0;
 wire [0:11] w2;
 wire [0:11] w3;
 wire [0:11] w4;
 assign v4642b6 = w0;
 assign w3 = v9f67dc;
 assign v9a4127 = w4;
 v9447a6 v0a8266 (
  .v4642b6(w0),
  .v87587b(w2),
  .v105ee0(w3),
  .vaf8eaa(w4)
 );
 v20620a #(
  .vc5c8ea(p1)
 ) v143800 (
  .v863e2b(w2)
 );
endmodule

//---------------------------------------------------
//-- AdderK-12bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderK-12bit: Adder of 12-bit operand and 12-bit constant
//---------------------------------------------------
//---- Top entity
module v9447a6 (
 input [11:0] v87587b,
 input [11:0] v105ee0,
 output v4642b6,
 output [11:0] vaf8eaa
);
 wire w0;
 wire w1;
 wire [0:7] w2;
 wire [0:11] w3;
 wire [0:11] w4;
 wire [0:11] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire [0:7] w8;
 wire [0:3] w9;
 wire [0:7] w10;
 assign v4642b6 = w0;
 assign w3 = v87587b;
 assign w4 = v105ee0;
 assign vaf8eaa = w5;
 vcb23aa v8e0bba (
  .v4642b6(w1),
  .v62bf25(w2),
  .v39966a(w8),
  .veb2f59(w10)
 );
 vc97ea6 v28c516 (
  .v1215c2(w4),
  .v51ed6c(w9),
  .vc673c0(w10)
 );
 vc97ea6 vd39f64 (
  .v1215c2(w3),
  .v51ed6c(w7),
  .vc673c0(w8)
 );
 va1ce30 v4e95c7 (
  .v4642b6(w0),
  .vb9cfc3(w1),
  .v817794(w6),
  .v0550b6(w7),
  .v24708e(w9)
 );
 vf8299b v073a55 (
  .v643efe(w2),
  .vb04f06(w5),
  .v21c161(w6)
 );
endmodule

//---------------------------------------------------
//-- Adder-12bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-12bits: Adder of two operands of 12 bits
//---------------------------------------------------
//---- Top entity
module vcb23aa (
 input [7:0] v39966a,
 input [7:0] veb2f59,
 output v4642b6,
 output [7:0] v62bf25
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:7] w4;
 wire w5;
 wire w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 assign w0 = veb2f59;
 assign w1 = v39966a;
 assign v62bf25 = w4;
 assign v4642b6 = w5;
 v6bdcd9 vd88c66 (
  .vcc8c7c(w0),
  .v651522(w9),
  .v2cc41f(w10)
 );
 v6bdcd9 v26a0bb (
  .vcc8c7c(w1),
  .v651522(w7),
  .v2cc41f(w8)
 );
 v25966b v9ea427 (
  .v817794(w3),
  .v4642b6(w6),
  .v0550b6(w8),
  .v24708e(w10)
 );
 vafb28f vc75346 (
  .v515fe7(w2),
  .v3c88fc(w3),
  .va9ac17(w4)
 );
 va1ce30 v40c17f (
  .v817794(w2),
  .v4642b6(w5),
  .vb9cfc3(w6),
  .v0550b6(w7),
  .v24708e(w9)
 );
endmodule

//---------------------------------------------------
//-- Adder-8bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-8bits: Adder of two operands of 8 bits
//---------------------------------------------------
//---- Top entity
module v25966b (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 v1ea21d vdbe125 (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w14),
  .v82de4f(w17)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w12),
  .v82de4f(w16)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w13),
  .vda577d(w16),
  .v3f8943(w17),
  .v64d863(w18)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w11),
  .vda577d(w12),
  .v3f8943(w14),
  .v64d863(w15)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w11),
  .v82de4f(w13)
 );
endmodule

//---------------------------------------------------
//-- Adder-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-4bits: Adder of two operands of 4 bits
//---------------------------------------------------
//---- Top entity
module v1ea21d (
 input v27dec4,
 input v82de4f,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v82de4f;
 assign w1 = v27dec4;
 assign v4642b6 = w3;
 assign v8e8a67 = w4;
 vad119b vb820a1 (
  .v82de4f(w0),
  .v27dec4(w1),
  .v0ef266(w2),
  .v4642b6(w3),
  .v8e8a67(w4)
 );
 vd30ca9 v23ebb6 (
  .v9fb85f(w2)
 );
endmodule

//---------------------------------------------------
//-- Adder-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-1bit: Adder of two operands of 1 bit
//---------------------------------------------------
//---- Top entity
module vad119b (
 input v27dec4,
 input v82de4f,
 input v0ef266,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign v8e8a67 = w1;
 assign v4642b6 = w5;
 assign w6 = v27dec4;
 assign w7 = v27dec4;
 assign w8 = v82de4f;
 assign w9 = v82de4f;
 assign w10 = v0ef266;
 assign w11 = v0ef266;
 assign w2 = w0;
 assign w7 = w6;
 assign w9 = w8;
 assign w11 = w10;
 vd12401 v2e3d9f (
  .vcbab45(w0),
  .v0e28cb(w7),
  .v3ca442(w9)
 );
 vd12401 vb50462 (
  .v0e28cb(w0),
  .vcbab45(w1),
  .v3ca442(w11)
 );
 vba518e v4882f4 (
  .v3ca442(w2),
  .vcbab45(w3),
  .v0e28cb(w10)
 );
 vba518e v8fcf41 (
  .vcbab45(w4),
  .v0e28cb(w6),
  .v3ca442(w8)
 );
 v873425 vc5b8b9 (
  .v3ca442(w3),
  .v0e28cb(w4),
  .vcbab45(w5)
 );
endmodule

//---------------------------------------------------
//-- AdderC-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-1bit: Adder of two operands of 1 bit plus the carry in
//---------------------------------------------------
//---- Top entity
module vd12401 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vd12401_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: two bits input xor gate
//---------------------------------------------------

module vd12401_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 0
//---------------------------------------------------

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module va1ce30 (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 input vb9cfc3,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 assign w11 = vb9cfc3;
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w13),
  .v82de4f(w17)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w14),
  .vda577d(w17),
  .v3f8943(w18),
  .v64d863(w19)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w12),
  .vda577d(w13),
  .v3f8943(w15),
  .v64d863(w16)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w12),
  .v82de4f(w14)
 );
 vad119b v3599be (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v0ef266(w11),
  .v27dec4(w16),
  .v82de4f(w19)
 );
endmodule

//---------------------------------------------------
//-- AdderC-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-4bits: Adder of two operands of 4 bits and Carry in
//---------------------------------------------------
//---- Top entity
module vc97ea6 (
 input [11:0] v1215c2,
 output [3:0] v51ed6c,
 output [7:0] vc673c0
);
 wire [0:3] w0;
 wire [0:11] w1;
 wire [0:7] w2;
 assign v51ed6c = w0;
 assign w1 = v1215c2;
 assign vc673c0 = w2;
 vc97ea6_v9a2a06 v9a2a06 (
  .o1(w0),
  .i(w1),
  .o0(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus12-Split-4-8
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus12-Split-4-8: Split the 12-bits bus into two buses of 4 and 8 wires
//---------------------------------------------------

module vc97ea6_v9a2a06 (
 input [11:0] i,
 output [3:0] o1,
 output [7:0] o0
);
 
 assign o1 = i[11:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module vf8299b (
 input [3:0] v21c161,
 input [7:0] v643efe,
 output [11:0] vb04f06
);
 wire [0:11] w0;
 wire [0:7] w1;
 wire [0:3] w2;
 assign vb04f06 = w0;
 assign w1 = v643efe;
 assign w2 = v21c161;
 vf8299b_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus12-Join-4-8
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus12-Join-4-8: Join the two buses into an 12-bits Bus
//---------------------------------------------------

module vf8299b_v9a2a06 (
 input [3:0] i1,
 input [7:0] i0,
 output [11:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v20620a #(
 parameter vc5c8ea = 0
) (
 output [11:0] v863e2b
);
 localparam p0 = vc5c8ea;
 wire [0:11] w1;
 assign v863e2b = w1;
 v20620a_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 12-bits-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Generic: 12-bits generic constant (0-4095)
//---------------------------------------------------

module v20620a_v465065 #(
 parameter VALUE = 0
) (
 output [11:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module vbc6704 (
 input [7:0] v595263,
 output vc85478,
 output v7ada3f,
 output v2c9812,
 output ve0c1b4,
 output v7c37b3,
 output v8f149e,
 output vb85197,
 output v45ab8c
);
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign w0 = v595263;
 assign vc85478 = w1;
 assign v7ada3f = w2;
 assign v2c9812 = w3;
 assign ve0c1b4 = w4;
 assign v7c37b3 = w5;
 assign v8f149e = w6;
 assign vb85197 = w7;
 assign v45ab8c = w8;
 vbc6704_v9a2a06 v9a2a06 (
  .i(w0),
  .o7(w1),
  .o6(w2),
  .o5(w3),
  .o4(w4),
  .o3(w5),
  .o2(w6),
  .o1(w7),
  .o0(w8)
 );
endmodule

//---------------------------------------------------
//-- Separador-bus
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Separador de bus de 8-bits en 8 cables
//---------------------------------------------------

module vbc6704_v9a2a06 (
 input [7:0] i,
 output o7,
 output o6,
 output o5,
 output o4,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o7 = i[7];
 assign o6 = i[6];
 assign o5 = i[5];
 assign o4 = i[4];
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule

module main_v6e4b35 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 reg [15:0] counter;
 reg out = 1'b0;
 
 always @(posedge clk_in) begin
   counter <= counter + 1;
   if(counter == N / 2) begin
     counter <= 0;
     out <= ~out;
   end
 end
 
 assign clk_out = out;
endmodule

module main_vdb0040 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 reg [15:0] counter;
 reg out = 1'b0;
 
 always @(posedge clk_in) begin
   counter <= counter + 1;
   if(counter == N / 2) begin
     counter <= 0;
     out <= ~out;
   end
 end
 
 assign clk_out = out;
endmodule

module main_v273ad7 #(
 parameter ROMFILE = 0
) (
 input clk,
 input [11:0] A,
 output [15:0] D
);
 reg [15:0] rom [0:4095];
 wire [11:0] A;
 reg [15:0] D;
 
 always @(negedge clk) begin
   D <= rom[A];
 end
 
 initial begin
     if (ROMFILE) $readmemh(ROMFILE, rom);
 end
 
endmodule

module main_vb22799 (
 input clk_in,
 output [3:0] out
);
 reg out;
 
 always @(posedge clk_in)
   out <= out + 1;
endmodule

module main_vc78599 #(
 parameter ROMFILE = 0
) (
 input clk,
 input [3:0] A,
 output [7:0] D
);
 reg [7:0] rom [0:15];
 wire [3:0] A;
 reg [7:0] D;
 
 always @(negedge clk) begin
   D <= rom[A];
 end
 
 initial begin
     if (ROMFILE) $readmemh(ROMFILE, rom);
 end
endmodule
