// Code generated by Icestudio 0.9.0

`default_nettype none

//---- Top entity
module main #(
 parameter v12abe4 = 0,
 parameter vdf99d4 = 0,
 parameter v450104 = 0,
 parameter vc6a27d = 10,
 parameter vc8c55a = 2048,
 parameter v5e95af = 3,
 parameter v3381dc = 5
) (
 input vd07f87,
 input v0ccead,
 input v3c94e4,
 input vclk,
 output [7:0] v5fb12d,
 output v2584ac,
 output v02769e,
 output vd4cb56
);
 localparam p0 = vdf99d4;
 localparam p1 = v12abe4;
 localparam p2 = v450104;
 localparam p3 = vc6a27d;
 localparam p5 = v5e95af;
 localparam p7 = vc8c55a;
 localparam p10 = v3381dc;
 wire w4;
 wire [0:15] w6;
 wire [0:15] w8;
 wire [0:15] w9;
 wire w11;
 wire w12;
 wire [0:1] w13;
 wire w14;
 wire [0:10] w15;
 wire [0:10] w16;
 wire [0:15] w17;
 wire [0:15] w18;
 wire [0:15] w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire [0:15] w27;
 wire [0:7] w28;
 wire w29;
 wire w30;
 wire w31;
 wire [0:1] w32;
 wire w33;
 wire w34;
 wire [0:15] w35;
 wire w36;
 wire w37;
 wire w38;
 wire w39;
 wire w40;
 wire w41;
 wire w42;
 wire [0:10] w43;
 wire [0:15] w44;
 wire w45;
 assign w20 = v0ccead;
 assign w21 = vd07f87;
 assign w22 = v3c94e4;
 assign v5fb12d = w28;
 assign v2584ac = w39;
 assign vd4cb56 = w40;
 assign v02769e = w42;
 assign w45 = vclk;
 assign w9 = w6;
 assign w18 = w6;
 assign w18 = w9;
 assign w19 = w6;
 assign w19 = w9;
 assign w19 = w18;
 assign w23 = w4;
 assign w29 = w14;
 assign w33 = w31;
 assign w34 = w31;
 assign w34 = w33;
 assign w35 = w27;
 assign w37 = w36;
 assign w38 = w14;
 assign w38 = w29;
 assign w40 = w14;
 assign w40 = w29;
 assign w40 = w38;
 assign w41 = w31;
 assign w41 = w33;
 assign w41 = w34;
 assign w42 = w31;
 assign w42 = w33;
 assign w42 = w34;
 assign w42 = w41;
 assign w44 = w27;
 assign w44 = w35;
 ve2b7eb #(
  .vecb3d5(p0),
  .ve58c06(p1),
  .v204bed(p2)
 ) vcd20b5 (
  .v3ead5b(w4),
  .v328508(w45)
 );
 v2d0f3d #(
  .vf37482(p3)
 ) v37982d (
  .v090026(w4),
  .v1eee64(w31)
 );
 v2a4730 v1f9b0b (
  .v551ad3(w6),
  .v2dc030(w8),
  .v6dda25(w36)
 );
 v167d0d #(
  .v16d6b8(p5)
 ) v266b66 (
  .ve03bff(w6),
  .v18e78c(w11)
 );
 v34688e #(
  .vc5c8ea(p7)
 ) v252b85 (
  .v366f99(w8)
 );
 v01f7d8 #(
  .v6b316b(p10)
 ) v005980 (
  .v044a4b(w9),
  .v18e78c(w12)
 );
 v528969 v392af2 (
  .v0e28cb(w11),
  .v3ca442(w12),
  .vcbab45(w14)
 );
 vd4bd04 v037e3e (
  .v67a3fc(w13),
  .v03aaf0(w14),
  .vee8a83(w30)
 );
 main_ve05a11 ve05a11 (
  .out(w15),
  .in(w17)
 );
 main_v99f0fb v99f0fb (
  .out(w16),
  .in(w19)
 );
 main_vbe31e8 vbe31e8 (
  .data_in(w13),
  .addr_wr(w15),
  .addr_rd(w16),
  .data_out(w32),
  .clk(w37)
 );
 vbc66d7 vfcd64f (
  .v2c4251(w17),
  .v1489e0(w18),
  .v603a9a(w35)
 );
 v8b85ac vaffc02 (
  .v6018d0(w20),
  .v67441f(w21),
  .v11c145(w22),
  .v7d1720(w23),
  .v1931f3(w24),
  .vdf1a51(w25),
  .v80f8c4(w26)
 );
 vf038cb v05dee2 (
  .v830825(w24),
  .vf5ed18(w25),
  .v118736(w26),
  .v8687c5(w27)
 );
 v26f57a vdd974f (
  .vad1323(w27),
  .vf774e8(w28)
 );
 v8b89a5 v1f1ee4 (
  .vef4cea(w29),
  .vc24d9f(w30),
  .vb55943(w31)
 );
 main_vf9bf78 vf9bf78 (
  .in(w32),
  .clk(w33)
 );
 v82041a v7dd809 (
  .vef4cea(w34),
  .vc24d9f(w36)
 );
 v93a77a v87a4f4 (
  .v89e67d(w38),
  .ve89523(w39),
  .vca22e9(w41),
  .vc66fc3(w43)
 );
 main_vc7cb5c vc7cb5c (
  .out(w43),
  .in(w44)
 );
endmodule

//---- Top entity
module ve2b7eb #(
 parameter ve58c06 = 0,
 parameter vecb3d5 = 79,
 parameter v204bed = 4,
 parameter vd29ea2 = 1,
 parameter v16d365 = "SIMPLE"
) (
 input v328508,
 output vdbfa46,
 output v3ead5b,
 output v333bf4
);
 localparam p0 = ve58c06;
 localparam p1 = vecb3d5;
 localparam p2 = v204bed;
 localparam p3 = vd29ea2;
 localparam p4 = v16d365;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 assign vdbfa46 = w7;
 assign v3ead5b = w8;
 assign v333bf4 = w9;
 assign w10 = v328508;
 vc83dcd va0dc84 (
  .v608bd9(w5)
 );
 vc4dd08 vda5929 (
  .v608bd9(w6)
 );
 ve2b7eb_vd4bd9d #(
  .DIVR(p0),
  .DIVF(p1),
  .DIVQ(p2),
  .FILTER_RANGE(p3),
  .FEEDBACK_PATH(p4)
 ) vd4bd9d (
  .RESETB(w5),
  .BYPASS(w6),
  .PLLOUTGLOBAL(w7),
  .PLLOUTCORE(w8),
  .LOCK(w9),
  .PACKAGEPIN(w10)
 );
endmodule

//---------------------------------------------------
//-- PLL40_PAD
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- SB_PLL40_PAD
//---------------------------------------------------

module ve2b7eb_vd4bd9d #(
 parameter DIVR = 0,
 parameter DIVF = 0,
 parameter DIVQ = 0,
 parameter FILTER_RANGE = 0,
 parameter FEEDBACK_PATH = 0
) (
 input PACKAGEPIN,
 input RESETB,
 input BYPASS,
 output PLLOUTGLOBAL,
 output PLLOUTCORE,
 output LOCK
);
 SB_PLL40_PAD #(
 		.FEEDBACK_PATH("SIMPLE"),
 		.DIVR(DIVR),		// DIVR =  0
 		.DIVF(DIVF),	// DIVF = 79
 		.DIVQ(DIVQ),		// DIVQ =  4
 		.FILTER_RANGE(FILTER_RANGE)	// FILTER_RANGE = 1
 	) uut (
 		.LOCK(LOCK),
 		.RESETB(RESETB),
 		.BYPASS(BYPASS),
 		.PACKAGEPIN(PACKAGEPIN),
 		.PLLOUTCORE(PLLOUTCORE),
 		.PLLOUTGLOBAL(PLLOUTGLOBAL)
 		);
endmodule
//---- Top entity
module vc83dcd (
 output v608bd9
);
 wire w0;
 assign v608bd9 = w0;
 vc83dcd_v68c173 v68c173 (
  .v(w0)
 );
endmodule

//---------------------------------------------------
//-- Bit 1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Assign 1 to the output wire
//---------------------------------------------------

module vc83dcd_v68c173 (
 output v
);
 // Bit 1
 
 assign v = 1'b1;
endmodule
//---- Top entity
module vc4dd08 (
 output v608bd9
);
 wire w0;
 assign v608bd9 = w0;
 vc4dd08_v68c173 v68c173 (
  .v(w0)
 );
endmodule

//---------------------------------------------------
//-- Bit 0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Assign 0 to the output wire
//---------------------------------------------------

module vc4dd08_v68c173 (
 output v
);
 // Bit 0
 
 assign v = 1'b0;
endmodule
//---- Top entity
module v2d0f3d #(
 parameter vf37482 = 20
) (
 input v090026,
 output v1eee64
);
 localparam p0 = vf37482;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign w1 = v090026;
 assign w5 = v090026;
 assign w6 = v090026;
 assign w7 = v090026;
 assign v1eee64 = w8;
 assign w5 = w1;
 assign w6 = w1;
 assign w6 = w5;
 assign w7 = w1;
 assign w7 = w5;
 assign w7 = w6;
 v2d0f3d_v10564b #(
  .N(p0)
 ) v10564b (
  .clk_in(w1),
  .clk_out(w2)
 );
 v8b89a5 ve5e06f (
  .vef4cea(w3),
  .vc24d9f(w4),
  .vb55943(w6)
 );
 v8b89a5 vfca5d6 (
  .vef4cea(w2),
  .vc24d9f(w3),
  .vb55943(w5)
 );
 v8b89a5 v09e944 (
  .vef4cea(w4),
  .vb55943(w7),
  .vc24d9f(w8)
 );
endmodule


module v2d0f3d_v10564b #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 reg [15:0] counter;
 reg out = 1'b0;
 
 always @(posedge clk_in) begin
   counter <= counter + 1;
   if(counter == (N / 2) - 1) begin
     counter <= 0;
     out <= ~out;
   end
 end
 
 assign clk_out = out;
endmodule
//---- Top entity
module v8b89a5 (
 input vb55943,
 input vef4cea,
 output vc24d9f
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = vef4cea;
 assign w1 = vb55943;
 assign vc24d9f = w2;
 v8b89a5_v526aa2 v526aa2 (
  .d(w0),
  .clk(w1),
  .q(w2)
 );
endmodule

//---------------------------------------------------
//-- Flip-flop D
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Delay flip-flop
//---------------------------------------------------

module v8b89a5_v526aa2 (
 input clk,
 input d,
 output q
);
 // D flip-flop
 
 reg q = 1'b0;
 
 always @(posedge clk)
 begin
   q <= d;
 end
 
 
endmodule
//---- Top entity
module v2a4730 (
 input v6dda25,
 input [15:0] v2dc030,
 output [15:0] v551ad3,
 output ve37344
);
 wire [0:15] w0;
 wire w1;
 wire [0:15] w2;
 wire [0:15] w3;
 wire w4;
 wire w5;
 assign w1 = v6dda25;
 assign v551ad3 = w2;
 assign w3 = v2dc030;
 assign ve37344 = w4;
 assign w2 = w0;
 assign w5 = w4;
 v413e4a v52120f (
  .v49911e(w0),
  .v6dda25(w1),
  .ve556f1(w5)
 );
 v3556c3 vc9e25f (
  .v6d9caf(w0),
  .veb1f69(w3),
  .v4642b6(w4)
 );
endmodule

//---------------------------------------------------
//-- syscounter-M-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- syscounter-M-16-bits: 16-bits Module M Syscounter
//---------------------------------------------------
//---- Top entity
module v413e4a (
 input v6dda25,
 input ve556f1,
 output [15:0] v49911e,
 output ve37344
);
 wire w0;
 wire [0:15] w1;
 wire [0:15] w2;
 wire w3;
 wire [0:15] w4;
 wire w5;
 assign w0 = ve556f1;
 assign w3 = v6dda25;
 assign v49911e = w4;
 assign ve37344 = w5;
 assign w4 = w1;
 vbc711b v8fa00b (
  .v782748(w0),
  .v3f90b8(w1),
  .vc320da(w2),
  .v6dda25(w3)
 );
 v8ecd59 v9392cd (
  .v2f9d57(w1),
  .vd7988b(w2),
  .v4642b6(w5)
 );
endmodule

//---------------------------------------------------
//-- syscounter-rst-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 16-bits Syscounter with reset
//---------------------------------------------------
//---- Top entity
module vbc711b (
 input v6dda25,
 input v782748,
 input [15:0] vc320da,
 output [15:0] v3f90b8
);
 wire [0:15] w0;
 wire [0:15] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w0 = vc320da;
 assign v3f90b8 = w1;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w14 = v782748;
 assign w15 = v782748;
 assign w16 = v782748;
 assign w17 = v782748;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w15 = w14;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 v5c75f6 vbdef88 (
  .v4de61b(w2),
  .v50034e(w6),
  .v6dda25(w13),
  .v782748(w17)
 );
 v5c75f6 v6188f9 (
  .v4de61b(w3),
  .v50034e(w7),
  .v6dda25(w12),
  .v782748(w16)
 );
 v852bc8 vd47660 (
  .v91b9c1(w0),
  .v527ffb(w2),
  .v71a717(w3),
  .v0b337e(w4),
  .vfc89f9(w5)
 );
 v401a28 v3ef916 (
  .v14a530(w1),
  .vcc76e8(w6),
  .vd531e6(w7),
  .v7ef7d6(w8),
  .v1447f2(w9)
 );
 v5c75f6 v9f7443 (
  .v4de61b(w4),
  .v50034e(w8),
  .v6dda25(w11),
  .v782748(w15)
 );
 v5c75f6 vd2d6b6 (
  .v4de61b(w5),
  .v50034e(w9),
  .v6dda25(w10),
  .v782748(w14)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x16
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x16: 16 D flip-flops in paralell with reset
//---------------------------------------------------
//---- Top entity
module v5c75f6 (
 input v6dda25,
 input v782748,
 input [3:0] v4de61b,
 output [3:0] v50034e
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w6 = v4de61b;
 assign v50034e = w7;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w14 = v782748;
 assign w15 = v782748;
 assign w16 = v782748;
 assign w17 = v782748;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w15 = w14;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 vc4f23a v4b1225 (
  .v3f8943(w2),
  .v64d863(w3),
  .vda577d(w4),
  .v985fcb(w6),
  .v4f1fd3(w8)
 );
 v84f0a1 v6491fd (
  .v03aaf0(w0),
  .vee8a83(w1),
  .vf8041d(w5),
  .v11bca5(w7),
  .vd84a57(w9)
 );
 v2be0f8 v10a04f (
  .v4642b6(w0),
  .vf354ee(w3),
  .vd53b77(w13),
  .v27dec4(w17)
 );
 v2be0f8 v7d9648 (
  .v4642b6(w1),
  .vf354ee(w2),
  .vd53b77(w12),
  .v27dec4(w16)
 );
 v2be0f8 v004b14 (
  .vf354ee(w4),
  .v4642b6(w5),
  .vd53b77(w11),
  .v27dec4(w15)
 );
 v2be0f8 v8aa818 (
  .vf354ee(w8),
  .v4642b6(w9),
  .vd53b77(w10),
  .v27dec4(w14)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x04
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x04: Three D flip-flops in paralell with reset
//---------------------------------------------------
//---- Top entity
module vc4f23a (
 input [3:0] v985fcb,
 output v4f1fd3,
 output vda577d,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign vda577d = w2;
 assign v4f1fd3 = w3;
 assign w4 = v985fcb;
 vc4f23a_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .o2(w2),
  .o3(w3),
  .i(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Split-all: Split the 4-bits bus into its wires
//---------------------------------------------------

module vc4f23a_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v84f0a1 (
 input vd84a57,
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [3:0] v11bca5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign w2 = vf8041d;
 assign w3 = vd84a57;
 assign v11bca5 = w4;
 v84f0a1_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .i2(w2),
  .i3(w3),
  .o(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Join-all: Join all the wires into a 4-bits Bus
//---------------------------------------------------

module v84f0a1_v9a2a06 (
 input i3,
 input i2,
 input i1,
 input i0,
 output [3:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module v2be0f8 #(
 parameter vbd3217 = 0
) (
 input vd53b77,
 input v27dec4,
 input vf354ee,
 output v4642b6
);
 localparam p5 = vbd3217;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w6;
 assign w2 = v27dec4;
 assign w3 = vf354ee;
 assign v4642b6 = w4;
 assign w6 = vd53b77;
 v3676a0 v7539bf (
  .vcbab45(w1),
  .v0e28cb(w2)
 );
 vba518e vfe8158 (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w3)
 );
 v053dc2 #(
  .v71e305(p5)
 ) vd104a4 (
  .vf54559(w0),
  .ve8318d(w4),
  .va4102a(w6)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x01
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x01: D Flip flop with reset input. When rst=1, the DFF is 0
//---------------------------------------------------
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT gate (Verilog implementation)
//---------------------------------------------------

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Two bits input And gate
//---------------------------------------------------

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module v053dc2 #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v053dc2_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- DFF
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- D Flip-flop (verilog implementation)
//---------------------------------------------------

module v053dc2_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg q = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   q <= d;
endmodule
//---- Top entity
module v852bc8 (
 input [15:0] v91b9c1,
 output [3:0] vfc89f9,
 output [3:0] v0b337e,
 output [3:0] v71a717,
 output [3:0] v527ffb
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 assign w0 = v91b9c1;
 assign v527ffb = w1;
 assign v71a717 = w2;
 assign v0b337e = w3;
 assign vfc89f9 = w4;
 v852bc8_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Split-quarter
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Split-quarter: Split the 16-bits bus into four buses of the same size
//---------------------------------------------------

module v852bc8_v9a2a06 (
 input [15:0] i,
 output [3:0] o3,
 output [3:0] o2,
 output [3:0] o1,
 output [3:0] o0
);
 assign o3 = i[15:12];
 assign o2 = i[11:8];
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v401a28 (
 input [3:0] v1447f2,
 input [3:0] v7ef7d6,
 input [3:0] vd531e6,
 input [3:0] vcc76e8,
 output [15:0] v14a530
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 assign v14a530 = w0;
 assign w1 = vcc76e8;
 assign w2 = vd531e6;
 assign w3 = v7ef7d6;
 assign w4 = v1447f2;
 v401a28_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Join-quarter
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Join-quarter: Join the four same buses into an 16-bits Bus
//---------------------------------------------------

module v401a28_v9a2a06 (
 input [3:0] i3,
 input [3:0] i2,
 input [3:0] i1,
 input [3:0] i0,
 output [15:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module v8ecd59 #(
 parameter v6c5139 = 1
) (
 input [15:0] v2f9d57,
 output v4642b6,
 output [15:0] vd7988b
);
 localparam p1 = v6c5139;
 wire w0;
 wire [0:15] w2;
 wire [0:15] w3;
 assign v4642b6 = w0;
 assign w2 = v2f9d57;
 assign vd7988b = w3;
 v265696 #(
  .vd73390(p1)
 ) v76123a (
  .v4642b6(w0),
  .v36f2dd(w2),
  .vc068fb(w3)
 );
endmodule

//---------------------------------------------------
//-- Inc1-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Inc1-16bit: Increment a 16-bits number by one
//---------------------------------------------------
//---- Top entity
module v265696 #(
 parameter vd73390 = 0
) (
 input [15:0] v36f2dd,
 output v4642b6,
 output [15:0] vc068fb
);
 localparam p1 = vd73390;
 wire w0;
 wire [0:15] w2;
 wire [0:15] w3;
 wire [0:15] w4;
 assign v4642b6 = w0;
 assign w3 = v36f2dd;
 assign vc068fb = w4;
 v651fa3 #(
  .vc5c8ea(p1)
 ) vdd8fa2 (
  .vcd9338(w2)
 );
 vbc66d7 vce7ab7 (
  .v4642b6(w0),
  .v1489e0(w2),
  .v603a9a(w3),
  .v2c4251(w4)
 );
endmodule

//---------------------------------------------------
//-- AdderK-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderK-16bit: Adder of 16-bit operand and 16-bit constant
//---------------------------------------------------
//---- Top entity
module v651fa3 #(
 parameter vc5c8ea = 0
) (
 output [15:0] vcd9338
);
 localparam p0 = vc5c8ea;
 wire [0:15] w1;
 assign vcd9338 = w1;
 v651fa3_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 16-bits-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Generic: 16-bits generic constant
//---------------------------------------------------

module v651fa3_v465065 #(
 parameter VALUE = 0
) (
 output [15:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module vbc66d7 (
 input [15:0] v1489e0,
 input [15:0] v603a9a,
 output v4642b6,
 output [15:0] v2c4251
);
 wire w0;
 wire w1;
 wire [0:15] w2;
 wire [0:15] w3;
 wire [0:15] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:7] w9;
 wire [0:7] w10;
 assign v4642b6 = w0;
 assign w2 = v603a9a;
 assign w3 = v1489e0;
 assign v2c4251 = w4;
 v306ca3 v0a29fe (
  .v91b9c1(w2),
  .vef5eee(w9),
  .vd3ef3b(w10)
 );
 v306ca3 vb0a6ce (
  .v91b9c1(w3),
  .vef5eee(w7),
  .vd3ef3b(w8)
 );
 vcb23aa v8e0bba (
  .v4642b6(w1),
  .v62bf25(w6),
  .v39966a(w8),
  .veb2f59(w10)
 );
 vc3c498 v917bbf (
  .v4642b6(w0),
  .vb9cfc3(w1),
  .veeaa8e(w5),
  .v45c6ee(w7),
  .v20212e(w9)
 );
 v8cc49c v03c3e3 (
  .v14a530(w4),
  .vb334ae(w5),
  .v2b8a97(w6)
 );
endmodule

//---------------------------------------------------
//-- Adder-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-16bits: Adder of two operands of 16 bits
//---------------------------------------------------
//---- Top entity
module v306ca3 (
 input [15:0] v91b9c1,
 output [7:0] vef5eee,
 output [7:0] vd3ef3b
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = v91b9c1;
 assign vef5eee = w1;
 assign vd3ef3b = w2;
 v306ca3_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Split-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Split-half: Split the 16-bits bus into two buses of the same size
//---------------------------------------------------

module v306ca3_v9a2a06 (
 input [15:0] i,
 output [7:0] o1,
 output [7:0] o0
);
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module vcb23aa (
 input [7:0] v39966a,
 input [7:0] veb2f59,
 output v4642b6,
 output [7:0] v62bf25
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:7] w4;
 wire w5;
 wire w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 assign w0 = veb2f59;
 assign w1 = v39966a;
 assign v62bf25 = w4;
 assign v4642b6 = w5;
 v6bdcd9 vd88c66 (
  .vcc8c7c(w0),
  .v651522(w9),
  .v2cc41f(w10)
 );
 v6bdcd9 v26a0bb (
  .vcc8c7c(w1),
  .v651522(w7),
  .v2cc41f(w8)
 );
 v25966b v9ea427 (
  .v817794(w3),
  .v4642b6(w6),
  .v0550b6(w8),
  .v24708e(w10)
 );
 vafb28f vc75346 (
  .v515fe7(w2),
  .v3c88fc(w3),
  .va9ac17(w4)
 );
 va1ce30 v40c17f (
  .v817794(w2),
  .v4642b6(w5),
  .vb9cfc3(w6),
  .v0550b6(w7),
  .v24708e(w9)
 );
endmodule

//---------------------------------------------------
//-- Adder-8bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-8bits: Adder of two operands of 8 bits
//---------------------------------------------------
//---- Top entity
module v6bdcd9 (
 input [7:0] vcc8c7c,
 output [3:0] v651522,
 output [3:0] v2cc41f
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign v651522 = w0;
 assign v2cc41f = w1;
 assign w2 = vcc8c7c;
 v6bdcd9_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus8-Split-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus8-Split-half: Split the 8-bits bus into two buses of the same size
//---------------------------------------------------

module v6bdcd9_v9a2a06 (
 input [7:0] i,
 output [3:0] o1,
 output [3:0] o0
);
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v25966b (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 v1ea21d vdbe125 (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w14),
  .v82de4f(w17)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w12),
  .v82de4f(w16)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w13),
  .vda577d(w16),
  .v3f8943(w17),
  .v64d863(w18)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w11),
  .vda577d(w12),
  .v3f8943(w14),
  .v64d863(w15)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w11),
  .v82de4f(w13)
 );
endmodule

//---------------------------------------------------
//-- Adder-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-4bits: Adder of two operands of 4 bits
//---------------------------------------------------
//---- Top entity
module v1ea21d (
 input v27dec4,
 input v82de4f,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v82de4f;
 assign w1 = v27dec4;
 assign v4642b6 = w3;
 assign v8e8a67 = w4;
 vad119b vb820a1 (
  .v82de4f(w0),
  .v27dec4(w1),
  .v0ef266(w2),
  .v4642b6(w3),
  .v8e8a67(w4)
 );
 vd30ca9 v23ebb6 (
  .v9fb85f(w2)
 );
endmodule

//---------------------------------------------------
//-- Adder-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-1bit: Adder of two operands of 1 bit
//---------------------------------------------------
//---- Top entity
module vad119b (
 input v27dec4,
 input v82de4f,
 input v0ef266,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign v8e8a67 = w1;
 assign v4642b6 = w5;
 assign w6 = v27dec4;
 assign w7 = v27dec4;
 assign w8 = v82de4f;
 assign w9 = v82de4f;
 assign w10 = v0ef266;
 assign w11 = v0ef266;
 assign w2 = w0;
 assign w7 = w6;
 assign w9 = w8;
 assign w11 = w10;
 vd12401 v2e3d9f (
  .vcbab45(w0),
  .v0e28cb(w7),
  .v3ca442(w9)
 );
 vd12401 vb50462 (
  .v0e28cb(w0),
  .vcbab45(w1),
  .v3ca442(w11)
 );
 vba518e v4882f4 (
  .v3ca442(w2),
  .vcbab45(w3),
  .v0e28cb(w10)
 );
 vba518e v8fcf41 (
  .vcbab45(w4),
  .v0e28cb(w6),
  .v3ca442(w8)
 );
 v873425 vc5b8b9 (
  .v3ca442(w3),
  .v0e28cb(w4),
  .vcbab45(w5)
 );
endmodule

//---------------------------------------------------
//-- AdderC-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-1bit: Adder of two operands of 1 bit plus the carry in
//---------------------------------------------------
//---- Top entity
module vd12401 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vd12401_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: two bits input xor gate
//---------------------------------------------------

module vd12401_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR2: Two bits input OR gate
//---------------------------------------------------

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 0
//---------------------------------------------------

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module vafb28f (
 input [3:0] v515fe7,
 input [3:0] v3c88fc,
 output [7:0] va9ac17
);
 wire [0:7] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign va9ac17 = w0;
 assign w1 = v515fe7;
 assign w2 = v3c88fc;
 vafb28f_v9a2a06 v9a2a06 (
  .o(w0),
  .i1(w1),
  .i0(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus8-Join-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus8-Join-half: Join the two same halves into an 8-bits Bus
//---------------------------------------------------

module vafb28f_v9a2a06 (
 input [3:0] i1,
 input [3:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module va1ce30 (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 input vb9cfc3,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 assign w11 = vb9cfc3;
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w13),
  .v82de4f(w17)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w14),
  .vda577d(w17),
  .v3f8943(w18),
  .v64d863(w19)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w12),
  .vda577d(w13),
  .v3f8943(w15),
  .v64d863(w16)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w12),
  .v82de4f(w14)
 );
 vad119b v3599be (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v0ef266(w11),
  .v27dec4(w16),
  .v82de4f(w19)
 );
endmodule

//---------------------------------------------------
//-- AdderC-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-4bits: Adder of two operands of 4 bits and Carry in
//---------------------------------------------------
//---- Top entity
module vc3c498 (
 input [7:0] v45c6ee,
 input [7:0] v20212e,
 input vb9cfc3,
 output v4642b6,
 output [7:0] veeaa8e
);
 wire w0;
 wire w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 wire [0:3] w11;
 assign w1 = vb9cfc3;
 assign w2 = v45c6ee;
 assign w3 = v20212e;
 assign veeaa8e = w4;
 assign v4642b6 = w7;
 v6bdcd9 v8d795a (
  .vcc8c7c(w3),
  .v651522(w10),
  .v2cc41f(w11)
 );
 v6bdcd9 v23dbc5 (
  .vcc8c7c(w2),
  .v651522(w8),
  .v2cc41f(w9)
 );
 vafb28f vef3a58 (
  .va9ac17(w4),
  .v3c88fc(w5),
  .v515fe7(w6)
 );
 va1ce30 v0ff71a (
  .v4642b6(w0),
  .vb9cfc3(w1),
  .v817794(w5),
  .v0550b6(w9),
  .v24708e(w11)
 );
 va1ce30 v12f94f (
  .vb9cfc3(w0),
  .v817794(w6),
  .v4642b6(w7),
  .v0550b6(w8),
  .v24708e(w10)
 );
endmodule

//---------------------------------------------------
//-- AdderC-8bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-8bits: Adder of two operands of 8 bits and Carry in
//---------------------------------------------------
//---- Top entity
module v8cc49c (
 input [7:0] vb334ae,
 input [7:0] v2b8a97,
 output [15:0] v14a530
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v14a530 = w0;
 assign w1 = v2b8a97;
 assign w2 = vb334ae;
 v8cc49c_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Join-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Join-half: Join the two same halves into an 16-bits Bus
//---------------------------------------------------

module v8cc49c_v9a2a06 (
 input [7:0] i1,
 input [7:0] i0,
 output [15:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v3556c3 (
 input [15:0] veb1f69,
 input [15:0] v6d9caf,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:15] w3;
 wire [0:15] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 assign v4642b6 = w0;
 assign w3 = veb1f69;
 assign w4 = v6d9caf;
 vba518e v707c6e (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w2)
 );
 vb2762a vb6832a (
  .v4642b6(w2),
  .v715730(w6),
  .vf191e6(w8)
 );
 v306ca3 v357be1 (
  .v91b9c1(w4),
  .vef5eee(w7),
  .vd3ef3b(w8)
 );
 v306ca3 v713b54 (
  .v91b9c1(w3),
  .vef5eee(w5),
  .vd3ef3b(w6)
 );
 vb2762a v302658 (
  .v4642b6(w1),
  .v715730(w5),
  .vf191e6(w7)
 );
endmodule

//---------------------------------------------------
//-- comp2-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comp2-16bit: Comparator of two 16-bit numbers
//---------------------------------------------------
//---- Top entity
module vb2762a (
 input [7:0] v715730,
 input [7:0] vf191e6,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire [0:3] w8;
 assign v4642b6 = w0;
 assign w3 = v715730;
 assign w4 = vf191e6;
 v438230 v577a36 (
  .v4642b6(w2),
  .v693354(w6),
  .v5369cd(w8)
 );
 vba518e v707c6e (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w2)
 );
 v6bdcd9 v921a9f (
  .vcc8c7c(w4),
  .v651522(w7),
  .v2cc41f(w8)
 );
 v6bdcd9 v8cfa4d (
  .vcc8c7c(w3),
  .v651522(w5),
  .v2cc41f(w6)
 );
 v438230 vfc1765 (
  .v4642b6(w1),
  .v693354(w5),
  .v5369cd(w7)
 );
endmodule

//---------------------------------------------------
//-- comp2-8bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comp2-8bit: Comparator of two 8-bit numbers
//---------------------------------------------------
//---- Top entity
module v438230 (
 input [3:0] v693354,
 input [3:0] v5369cd,
 output v4642b6
);
 wire w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 assign v4642b6 = w0;
 assign w1 = v693354;
 assign w2 = v5369cd;
 v23b15b v09a5a5 (
  .v4642b6(w3),
  .v27dec4(w12),
  .v6848e9(w14)
 );
 v23b15b vc1b29d (
  .v4642b6(w4),
  .v27dec4(w11),
  .v6848e9(w13)
 );
 v23b15b vcd27ce (
  .v4642b6(w5),
  .v27dec4(w9),
  .v6848e9(w10)
 );
 vc4f23a vea9c80 (
  .v985fcb(w1),
  .v4f1fd3(w7),
  .vda577d(w9),
  .v3f8943(w11),
  .v64d863(w12)
 );
 vc4f23a va7dcdc (
  .v985fcb(w2),
  .v4f1fd3(w8),
  .vda577d(w10),
  .v3f8943(w13),
  .v64d863(w14)
 );
 v23b15b va0849c (
  .v4642b6(w6),
  .v27dec4(w7),
  .v6848e9(w8)
 );
 veffd42 v6e3e65 (
  .vcbab45(w0),
  .v3ca442(w3),
  .v0e28cb(w4),
  .v033bf6(w5),
  .v9eb652(w6)
 );
endmodule

//---------------------------------------------------
//-- comp2-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comp2-4bit: Comparator of two 4-bit numbers
//---------------------------------------------------
//---- Top entity
module v23b15b (
 input v27dec4,
 input v6848e9,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w1 = v27dec4;
 assign v4642b6 = w2;
 assign w3 = v6848e9;
 vd12401 v955b2b (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w3)
 );
 v3676a0 vf92936 (
  .v0e28cb(w0),
  .vcbab45(w2)
 );
endmodule

//---------------------------------------------------
//-- comp2-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comp2-1bit: Comparator of two 1-bit numbers
//---------------------------------------------------
//---- Top entity
module veffd42 (
 input v9eb652,
 input v033bf6,
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = v3ca442;
 assign w1 = v9eb652;
 assign w2 = v033bf6;
 assign w3 = v0e28cb;
 assign vcbab45 = w4;
 vba518e vf3ef0f (
  .v3ca442(w0),
  .v0e28cb(w3),
  .vcbab45(w6)
 );
 vba518e vdcc53d (
  .v0e28cb(w1),
  .v3ca442(w2),
  .vcbab45(w5)
 );
 vba518e v17ac22 (
  .vcbab45(w4),
  .v0e28cb(w5),
  .v3ca442(w6)
 );
endmodule

//---------------------------------------------------
//-- AND4
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Three bits input And gate
//---------------------------------------------------
//---- Top entity
module v167d0d #(
 parameter v16d6b8 = 1
) (
 input [15:0] ve03bff,
 output v18e78c
);
 localparam p1 = v16d6b8;
 wire w0;
 wire [0:15] w2;
 assign v18e78c = w0;
 assign w2 = ve03bff;
 v167d0d_vd75681 #(
  .B(p1)
 ) vd75681 (
  .eq(w0),
  .a(w2)
 );
endmodule

//---------------------------------------------------
//-- Menor-que-1-op
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comparador menor que, de un operando de 16 bits
//---------------------------------------------------

module v167d0d_vd75681 #(
 parameter B = 0
) (
 input [15:0] a,
 output eq
);
 assign eq = (a < B);
endmodule
//---- Top entity
module v34688e #(
 parameter vc5c8ea = 0
) (
 output [15:0] v366f99
);
 localparam p0 = vc5c8ea;
 wire [0:15] w1;
 assign v366f99 = w1;
 v34688e_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- Constante-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Valor genérico constante, de 16 bits. Su valor se introduce como parámetro. Por defecto vale 0
//---------------------------------------------------

module v34688e_v465065 #(
 parameter VALUE = 0
) (
 output [15:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v01f7d8 #(
 parameter v6b316b = 0
) (
 input [15:0] v044a4b,
 output v18e78c
);
 localparam p1 = v6b316b;
 wire w0;
 wire [0:15] w2;
 assign v18e78c = w0;
 assign w2 = v044a4b;
 v01f7d8_vd75681 #(
  .K(p1)
 ) vd75681 (
  .eq(w0),
  .a(w2)
 );
endmodule

//---------------------------------------------------
//-- Comparador
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comparador de un operando de 16 bits. Se compara si el operando es igual al parámetro
//---------------------------------------------------

module v01f7d8_vd75681 #(
 parameter K = 0
) (
 input [15:0] a,
 output eq
);
 assign eq = (a == K);
endmodule
//---- Top entity
module v528969 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v528969_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR logic gate
//---------------------------------------------------

module v528969_vf4938a (
 input a,
 input b,
 output c
);
 // OR logic gate
 
 assign c = a | b;
endmodule
//---- Top entity
module vd4bd04 (
 input vee8a83,
 input v03aaf0,
 output [1:0] v67a3fc
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign v67a3fc = w2;
 vd4bd04_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

//---------------------------------------------------
//-- Agregador-bus
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Agregador de 2 cables en un bus de 2-bits
//---------------------------------------------------

module vd4bd04_v9a2a06 (
 input i1,
 input i0,
 output [1:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v8b85ac (
 input v67441f,
 input v6018d0,
 input v11c145,
 input v7d1720,
 output v1931f3,
 output vdf1a51,
 output v80f8c4
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 assign w6 = v67441f;
 assign w7 = v6018d0;
 assign w8 = v11c145;
 assign w9 = v7d1720;
 assign w10 = v7d1720;
 assign w11 = v7d1720;
 assign w12 = v7d1720;
 assign w13 = v7d1720;
 assign w14 = v7d1720;
 assign w15 = v7d1720;
 assign w16 = v7d1720;
 assign w17 = v7d1720;
 assign w21 = v7d1720;
 assign w22 = v7d1720;
 assign w23 = v7d1720;
 assign v1931f3 = w24;
 assign vdf1a51 = w25;
 assign v80f8c4 = w26;
 assign w10 = w9;
 assign w11 = w9;
 assign w11 = w10;
 assign w12 = w9;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w9;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w14 = w9;
 assign w14 = w10;
 assign w14 = w11;
 assign w14 = w12;
 assign w14 = w13;
 assign w15 = w9;
 assign w15 = w10;
 assign w15 = w11;
 assign w15 = w12;
 assign w15 = w13;
 assign w15 = w14;
 assign w16 = w9;
 assign w16 = w10;
 assign w16 = w11;
 assign w16 = w12;
 assign w16 = w13;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w9;
 assign w17 = w10;
 assign w17 = w11;
 assign w17 = w12;
 assign w17 = w13;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 assign w21 = w9;
 assign w21 = w10;
 assign w21 = w11;
 assign w21 = w12;
 assign w21 = w13;
 assign w21 = w14;
 assign w21 = w15;
 assign w21 = w16;
 assign w21 = w17;
 assign w22 = w9;
 assign w22 = w10;
 assign w22 = w11;
 assign w22 = w12;
 assign w22 = w13;
 assign w22 = w14;
 assign w22 = w15;
 assign w22 = w16;
 assign w22 = w17;
 assign w22 = w21;
 assign w23 = w9;
 assign w23 = w10;
 assign w23 = w11;
 assign w23 = w12;
 assign w23 = w13;
 assign w23 = w14;
 assign w23 = w15;
 assign w23 = w16;
 assign w23 = w17;
 assign w23 = w21;
 assign w23 = w22;
 v70ff7f v5d58c0 (
  .vc24d9f(w0),
  .vef4cea(w5),
  .vb55943(w14)
 );
 v70ff7f v09e2d9 (
  .vc24d9f(w1),
  .vef4cea(w4),
  .vb55943(w13)
 );
 v70ff7f vf3baed (
  .vef4cea(w0),
  .vb55943(w17),
  .vc24d9f(w20)
 );
 v70ff7f v60d4a6 (
  .vc24d9f(w2),
  .vef4cea(w3),
  .vb55943(w12)
 );
 v70ff7f v102611 (
  .vef4cea(w1),
  .vb55943(w16),
  .vc24d9f(w19)
 );
 v70ff7f vea0d90 (
  .vef4cea(w2),
  .vb55943(w15),
  .vc24d9f(w18)
 );
 v70ff7f vac2e8a (
  .vc24d9f(w5),
  .vef4cea(w8),
  .vb55943(w11)
 );
 v70ff7f v4b7de8 (
  .vc24d9f(w4),
  .vef4cea(w7),
  .vb55943(w10)
 );
 v70ff7f v3a9ca9 (
  .vc24d9f(w3),
  .vef4cea(w6),
  .vb55943(w9)
 );
 v70ff7f v9fa8a6 (
  .vef4cea(w20),
  .vb55943(w23),
  .vc24d9f(w26)
 );
 v70ff7f v7542a3 (
  .vef4cea(w19),
  .vb55943(w22),
  .vc24d9f(w25)
 );
 v70ff7f vbf5efc (
  .vef4cea(w18),
  .vb55943(w21),
  .vc24d9f(w24)
 );
endmodule

//---- Top entity
module v70ff7f (
 input vb55943,
 input vef4cea,
 output vc24d9f
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = vef4cea;
 assign w1 = vb55943;
 assign vc24d9f = w2;
 v70ff7f_v526aa2 v526aa2 (
  .d(w0),
  .clk(w1),
  .q(w2)
 );
endmodule

//---------------------------------------------------
//-- Flip-flop D
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Delay flip-flop
//---------------------------------------------------

module v70ff7f_v526aa2 (
 input clk,
 input d,
 output q
);
 // D flip-flop
 
 reg q = 1'b0;
 
 always @(posedge clk)
 begin
   q <= d;
 end
 
 
endmodule
//---- Top entity
module vf038cb (
 input v830825,
 input vf5ed18,
 input v118736,
 output [15:0] v8687c5,
 output v9f30c9
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire w2;
 wire [0:15] w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 assign v8687c5 = w3;
 assign w4 = v830825;
 assign v9f30c9 = w5;
 assign w6 = vf5ed18;
 assign w7 = v118736;
 assign w8 = v118736;
 assign w9 = vf5ed18;
 assign w8 = w7;
 assign w9 = w6;
 v8dd0ad v8efcf6 (
  .ve13d67(w0),
  .v59ca29(w2),
  .v7c48af(w4),
  .vcb13fe(w8),
  .vd2b237(w9)
 );
 v8dd0ad vdf6666 (
  .ve13d67(w1),
  .v7c48af(w2),
  .v59ca29(w5),
  .vd2b237(w6),
  .vcb13fe(w7)
 );
 v1e224f v10a621 (
  .v385b9c(w0),
  .vd34531(w1),
  .v4d4dee(w3)
 );
endmodule

//---- Top entity
module v8dd0ad (
 input v7c48af,
 input vd2b237,
 input vcb13fe,
 output [7:0] ve13d67,
 output v59ca29
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire [0:7] w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire w38;
 wire w39;
 wire w40;
 wire w41;
 assign w0 = v7c48af;
 assign v59ca29 = w7;
 assign ve13d67 = w9;
 assign w26 = vcb13fe;
 assign w27 = vcb13fe;
 assign w28 = vcb13fe;
 assign w29 = vcb13fe;
 assign w30 = vcb13fe;
 assign w31 = vcb13fe;
 assign w32 = vcb13fe;
 assign w33 = vcb13fe;
 assign w34 = vd2b237;
 assign w35 = vd2b237;
 assign w36 = vd2b237;
 assign w37 = vd2b237;
 assign w38 = vd2b237;
 assign w39 = vd2b237;
 assign w40 = vd2b237;
 assign w41 = vd2b237;
 assign w11 = w1;
 assign w13 = w2;
 assign w15 = w3;
 assign w17 = w4;
 assign w19 = w5;
 assign w21 = w6;
 assign w23 = w8;
 assign w25 = w7;
 assign w27 = w26;
 assign w28 = w26;
 assign w28 = w27;
 assign w29 = w26;
 assign w29 = w27;
 assign w29 = w28;
 assign w30 = w26;
 assign w30 = w27;
 assign w30 = w28;
 assign w30 = w29;
 assign w31 = w26;
 assign w31 = w27;
 assign w31 = w28;
 assign w31 = w29;
 assign w31 = w30;
 assign w32 = w26;
 assign w32 = w27;
 assign w32 = w28;
 assign w32 = w29;
 assign w32 = w30;
 assign w32 = w31;
 assign w33 = w26;
 assign w33 = w27;
 assign w33 = w28;
 assign w33 = w29;
 assign w33 = w30;
 assign w33 = w31;
 assign w33 = w32;
 assign w35 = w34;
 assign w36 = w34;
 assign w36 = w35;
 assign w37 = w34;
 assign w37 = w35;
 assign w37 = w36;
 assign w38 = w34;
 assign w38 = w35;
 assign w38 = w36;
 assign w38 = w37;
 assign w39 = w34;
 assign w39 = w35;
 assign w39 = w36;
 assign w39 = w37;
 assign w39 = w38;
 assign w40 = w34;
 assign w40 = w35;
 assign w40 = w36;
 assign w40 = w37;
 assign w40 = w38;
 assign w40 = w39;
 assign w41 = w34;
 assign w41 = w35;
 assign w41 = w36;
 assign w41 = w37;
 assign w41 = w38;
 assign w41 = w39;
 assign w41 = w40;
 v70ff7f v7118be (
  .vef4cea(w0),
  .vc24d9f(w1),
  .vb55943(w34)
 );
 v70ff7f v7e5dd2 (
  .vef4cea(w1),
  .vc24d9f(w2),
  .vb55943(w35)
 );
 v70ff7f va39ac4 (
  .vef4cea(w2),
  .vc24d9f(w3),
  .vb55943(w36)
 );
 v70ff7f v9a8657 (
  .vef4cea(w3),
  .vc24d9f(w4),
  .vb55943(w37)
 );
 v70ff7f v789aba (
  .vef4cea(w4),
  .vc24d9f(w5),
  .vb55943(w38)
 );
 v70ff7f vfe039c (
  .vef4cea(w5),
  .vc24d9f(w6),
  .vb55943(w39)
 );
 v70ff7f vf5baf3 (
  .vef4cea(w6),
  .vc24d9f(w8),
  .vb55943(w40)
 );
 v70ff7f v8c3660 (
  .vc24d9f(w7),
  .vef4cea(w8),
  .vb55943(w41)
 );
 v8dd0ad_v5a7c2b v5a7c2b (
  .o(w9),
  .i7(w10),
  .i6(w12),
  .i5(w14),
  .i4(w16),
  .i3(w18),
  .i2(w20),
  .i1(w22),
  .i0(w24)
 );
 v70ff7f vef6c05 (
  .vc24d9f(w10),
  .vef4cea(w11),
  .vb55943(w26)
 );
 v70ff7f v55d1fc (
  .vc24d9f(w12),
  .vef4cea(w13),
  .vb55943(w27)
 );
 v70ff7f v1577a8 (
  .vc24d9f(w14),
  .vef4cea(w15),
  .vb55943(w28)
 );
 v70ff7f v0d429a (
  .vc24d9f(w16),
  .vef4cea(w17),
  .vb55943(w29)
 );
 v70ff7f vfb6e30 (
  .vc24d9f(w18),
  .vef4cea(w19),
  .vb55943(w30)
 );
 v70ff7f v237d53 (
  .vc24d9f(w20),
  .vef4cea(w21),
  .vb55943(w31)
 );
 v70ff7f v721ec3 (
  .vc24d9f(w22),
  .vef4cea(w23),
  .vb55943(w32)
 );
 v70ff7f v4339fe (
  .vc24d9f(w24),
  .vef4cea(w25),
  .vb55943(w33)
 );
endmodule


module v8dd0ad_v5a7c2b (
 input i7,
 input i6,
 input i5,
 input i4,
 input i3,
 input i2,
 input i1,
 input i0,
 output [7:0] o
);
 assign o = {i0, i1, i2, i3, i4, i5, i6, i7};
endmodule
//---- Top entity
module v1e224f (
 input [7:0] v385b9c,
 input [7:0] vd34531,
 output [15:0] v4d4dee
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:15] w2;
 assign w0 = vd34531;
 assign w1 = v385b9c;
 assign v4d4dee = w2;
 v1e224f_v9a2a06 v9a2a06 (
  .i0(w0),
  .i1(w1),
  .o(w2)
 );
endmodule

//---------------------------------------------------
//-- Agregador-bus
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Agregador de 2 buses de 8-bits a bus de 16-bits
//---------------------------------------------------

module v1e224f_v9a2a06 (
 input [7:0] i1,
 input [7:0] i0,
 output [15:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v26f57a (
 input [15:0] vad1323,
 output [7:0] vf774e8,
 output [7:0] v0e9841
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:15] w2;
 assign v0e9841 = w0;
 assign vf774e8 = w1;
 assign w2 = vad1323;
 v26f57a_v9a2a06 v9a2a06 (
  .o0(w0),
  .o1(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Separador-bus
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Separador de bus de 16-bits en buses de 8 bits
//---------------------------------------------------

module v26f57a_v9a2a06 (
 input [15:0] i,
 output [7:0] o1,
 output [7:0] o0
);
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module v82041a (
 input vef4cea,
 output vc24d9f
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign vc24d9f = w0;
 assign w2 = vef4cea;
 assign w1 = w0;
 v70ff7f v082a97 (
  .vc24d9f(w0),
  .vb55943(w2),
  .vef4cea(w3)
 );
 v32200d v3c00a7 (
  .v0e28cb(w1),
  .vcbab45(w3)
 );
endmodule

//---------------------------------------------------
//-- Flip-flop T
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Toggle flip-flop
//---------------------------------------------------
//---- Top entity
module v32200d (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v32200d_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT logic gate
//---------------------------------------------------

module v32200d_vd54ca1 (
 input a,
 output c
);
 // NOT logic gate
 
 assign c = ~ a;
endmodule
//---- Top entity
module v93a77a #(
 parameter vbe43d2 = 2048
) (
 input v89e67d,
 input vca22e9,
 input [10:0] vc66fc3,
 output ve89523
);
 localparam p1 = vbe43d2;
 wire [0:15] w0;
 wire [0:15] w2;
 wire [0:1] w3;
 wire [0:10] w4;
 wire [0:10] w5;
 wire w6;
 wire w7;
 wire [0:1] w8;
 wire w9;
 wire w10;
 wire [0:15] w11;
 wire [0:10] w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign ve89523 = w7;
 assign w12 = vc66fc3;
 assign w13 = vca22e9;
 assign w14 = vca22e9;
 assign w15 = vca22e9;
 assign w16 = v89e67d;
 assign w17 = v89e67d;
 assign w10 = w9;
 assign w11 = w2;
 assign w14 = w13;
 assign w15 = w13;
 assign w15 = w14;
 assign w17 = w16;
 v2a4730 vbe3111 (
  .v2dc030(w0),
  .v551ad3(w2),
  .v6dda25(w9)
 );
 v34688e #(
  .vc5c8ea(p1)
 ) v8ea623 (
  .v366f99(w0)
 );
 vd4bd04 v58da9e (
  .v67a3fc(w3),
  .vee8a83(w6),
  .v03aaf0(w17)
 );
 v93a77a_v441977 v441977 (
  .in(w2),
  .out(w5)
 );
 v8b89a5 v6c3e9f (
  .vc24d9f(w6),
  .vb55943(w14),
  .vef4cea(w16)
 );
 v93a77a_v035ef0 v035ef0 (
  .out(w7),
  .in(w8),
  .clk(w15)
 );
 v82041a v96f019 (
  .vc24d9f(w9),
  .vef4cea(w13)
 );
 v93a77a_v8e6b5e v8e6b5e (
  .data_in(w3),
  .addr_wr(w4),
  .addr_rd(w5),
  .data_out(w8),
  .clk(w10)
 );
 v93a77a_v5d51a1 v5d51a1 (
  .out(w4),
  .in(w11),
  .delay(w12)
 );
endmodule


module v93a77a_v441977 (
 input [15:0] in,
 output [10:0] out
);
 assign out = in[10:0];
endmodule

module v93a77a_v035ef0 (
 input clk,
 input [1:0] in,
 output out
);
 reg bit = 0;
 
 always @(posedge clk)
 begin
   bit <= !bit;
   if(bit) out <= in[0];
   else out <= in[1];
 end
 
endmodule

module v93a77a_v8e6b5e #(
 parameter ROMF = 0
) (
 input clk,
 input [1:0] data_in,
 input [10:0] addr_wr,
 input [10:0] addr_rd,
 output [1:0] data_out
);
 //-- Address with
 localparam ADDR_WIDTH = 11;
 //-- Data with
 localparam DATA_WIDTH = 2;
 
 //-- Size of the memory
 localparam SIZE = 1 << ADDR_WIDTH;
 
 //-- Memory itself
 reg [DATA_WIDTH-1:0] mem[0:SIZE-1];
 
 //-- The data_out is a registered output (not a wire)
 reg data_out;
 
 //-- Reading port: Synchronous
 always @(posedge clk)
 begin
   mem[addr_wr] <= data_in;
   data_out <= mem[addr_rd];
 end
 
 
 //-- Init the memory
 initial begin
   
   if (ROMF)
     $readmemh(ROMF, mem, 0, SIZE-1);
   
 end
 
endmodule

module v93a77a_v5d51a1 (
 input [15:0] in,
 input [10:0] delay,
 output [10:0] out
);
 assign out = in[10:0] + delay;
endmodule

module main_ve05a11 (
 input [15:0] in,
 output [10:0] out
);
 assign out = in[10:0];
endmodule

module main_v99f0fb (
 input [15:0] in,
 output [10:0] out
);
 assign out = in[10:0];
endmodule

module main_vbe31e8 #(
 parameter ROMF = 0
) (
 input clk,
 input [10:0] addr_wr,
 input [10:0] addr_rd,
 input [1:0] data_in,
 output [1:0] data_out
);
 //-- Address with
 localparam ADDR_WIDTH = 11;
 //-- Data with
 localparam DATA_WIDTH = 2;
 
 //-- Size of the memory
 localparam SIZE = 1 << ADDR_WIDTH;
 
 //-- Memory itself
 reg [DATA_WIDTH-1:0] mem[0:SIZE-1];
 
 //-- The data_out is a registered output (not a wire)
 reg data_out;
 
 //-- Reading port: Synchronous
 always @(posedge clk)
 begin
   mem[addr_wr] <= data_in;
   data_out <= mem[addr_rd];
 end
 
 
 //-- Init the memory
 initial begin
   
   if (ROMF)
     $readmemh(ROMF, mem, 0, SIZE-1);
   
 end
 
endmodule

module main_vf9bf78 (
 input clk,
 input [1:0] in,
 output out
);
 reg bit = 0;
 
 always @(posedge clk)
 begin
   bit <= !bit;
   if(bit) out <= in[0];
   else out <= in[1];
 end
 
endmodule

module main_vc7cb5c (
 input [15:0] in,
 output [10:0] out
);
 assign out = in[10:0];
endmodule
